# Generated by Django 3.2.16 on 2023-08-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FeatureFlag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "flag_name",
                    models.CharField(max_length=300, verbose_name="Flag name"),
                ),
                (
                    "flag_value",
                    models.BooleanField(default=False, verbose_name="Flag value"),
                ),
            ],
        ),
    ]
