# Generated by Django 5.2.15 on 2026-06-09 17:45
from django.db import migrations
from django.core.exceptions import ObjectDoesNotExist


def rename_feature_flag(apps, schema_editor):
    feature_flag = apps.get_model("core", "FeatureFlag")
    empty_flags = feature_flag.objects.filter(flag_name="")

    if empty_flags.count() == 1:
        feature_flag_to_rename = empty_flags.first()
        feature_flag_to_rename.flag_name = "feature_flag_frozen_members"
        feature_flag_to_rename.save()


def reverse_rename_feature_flag(apps, schema_editor):
    feature_flag = apps.get_model("core", "FeatureFlag")
    try:
        feature_flag = feature_flag.objects.get(flag_name="feature_flag_frozen_members")
        feature_flag.flag_name = ""
        feature_flag.save()
    except ObjectDoesNotExist:
        pass


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(rename_feature_flag, reverse_rename_feature_flag),
    ]
