# Generated by Django 5.2.15 on 2026-06-09 17:45
from django.db import migrations
from django.core.exceptions import ObjectDoesNotExist


def rename_feature_flag(apps, schema_editor):
    FeatureFlag = apps.get_model("core", "FeatureFlag")
    empty_flags = FeatureFlag.objects.filter(flag_name="")

    if empty_flags.count() == 0:
        raise Exception("no feature flag with empty string found!")
    elif empty_flags.count() > 1:
        raise Exception(
            f"Found {empty_flags.count()} FeatureFlags with empty string! check manually!"
        )

    feature_flag = empty_flags.first()
    feature_flag.flag_name = "feature_flag_frozen_members"
    feature_flag.save()


def reverse_rename_feature_flag(apps, schema_editor):
    FeatureFlag = apps.get_model("core", "FeatureFlag")
    try:
        feature_flag = FeatureFlag.objects.get(flag_name="feature_flag_frozen_members")
        feature_flag.flag_name = ""
        feature_flag.save()
    except ObjectDoesNotExist:
        pass


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(rename_feature_flag, reverse_rename_feature_flag),
    ]
