# Generated by Django 3.1.7 on 2021-04-11 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="odoo_id",
            field=models.IntegerField(unique=True),
        ),
    ]
