# Generated by Django 3.1.7 on 2021-03-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="draftuser",
            name="birthdate",
            field=models.DateField(blank=True, null=True, verbose_name="Birthdate"),
        ),
    ]
