# Generated by Django 3.1.7 on 2021-03-28 07:34

from django.db import migrations, models
import ldapdb.models.fields
import tapir.accounts.validators


class Migration(migrations.Migration):

    dependencies = [
        ("coop", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DraftUser",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=150,
                        validators=[tapir.accounts.validators.UsernameValidator],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "num_shares",
                    ldapdb.models.fields.IntegerField(
                        default=1, verbose_name="Number of Shares"
                    ),
                ),
                (
                    "attended_welcome_session",
                    ldapdb.models.fields.BooleanField(
                        default=False, verbose_name="Attended Welcome Session"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
