# Generated by Django 3.1.7 on 2021-03-28 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coop", "0002_draftuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="draftuser",
            name="signed_membership_agreement",
            field=models.BooleanField(
                default=False, verbose_name="Signed Beteiligungserklärung"
            ),
        ),
        migrations.AlterField(
            model_name="draftuser",
            name="attended_welcome_session",
            field=models.BooleanField(
                default=False, verbose_name="Attended Welcome Session"
            ),
        ),
        migrations.AlterField(
            model_name="draftuser",
            name="num_shares",
            field=models.IntegerField(default=1, verbose_name="Number of Shares"),
        ),
    ]
