# Generated by Django 3.1.8 on 2021-05-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coop", "0003_auto_20210411_1012"),
    ]

    operations = [
        migrations.AddField(
            model_name="draftuser",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Phone number"
            ),
        ),
        migrations.AlterField(
            model_name="draftuser",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Email address"
            ),
        ),
        migrations.AlterField(
            model_name="draftuser",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="First name"
            ),
        ),
        migrations.AlterField(
            model_name="draftuser",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Last name"
            ),
        ),
    ]
