# Generated by Django 3.1.8 on 2021-05-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coop", "0005_draftuser_paid_membership_fee"),
    ]

    operations = [
        migrations.AddField(
            model_name="draftuser",
            name="preferred_language",
            field=models.CharField(
                choices=[("de", "Deutsch"), ("en", "English")],
                default="de",
                max_length=16,
                verbose_name="Preferred Language",
            ),
        ),
        migrations.AddField(
            model_name="shareowner",
            name="preferred_language",
            field=models.CharField(
                choices=[("de", "Deutsch"), ("en", "English")],
                default="de",
                max_length=16,
                verbose_name="Preferred Language",
            ),
        ),
    ]
