# Generated by Django 3.1.8 on 2021-05-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coop", "0006_auto_20210520_1353"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shareowner",
            name="preferred_language",
            field=models.CharField(
                blank=True,
                choices=[("de", "Deutsch"), ("en", "English")],
                default="de",
                max_length=16,
                verbose_name="Preferred Language",
            ),
        ),
    ]
