# Generated by Django 3.1.8 on 2021-05-28 17:35
from django.contrib.postgres.operations import UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("coop", "0007_auto_20210521_1139"),
    ]

    operations = [UnaccentExtension()]
