# Generated by Django 3.1.8 on 2021-05-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coop", "0008_auto_20210528_1735"),
    ]

    operations = [
        migrations.AddField(
            model_name="draftuser",
            name="from_startnext",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="draftuser",
            name="is_investing",
            field=models.BooleanField(default=False, verbose_name="Investing member"),
        ),
        migrations.AddField(
            model_name="shareowner",
            name="from_startnext",
            field=models.BooleanField(default=False),
        ),
    ]
