# Generated by Django 3.1.8 on 2021-06-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coop", "0010_auto_20210531_0833"),
    ]

    operations = [
        migrations.AddField(
            model_name="draftuser",
            name="startnext_welcome_email_sent",
            field=models.BooleanField(default=False),
        ),
    ]
