# Generated by Django 3.1.8 on 2021-06-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coop", "0011_draftuser_startnext_welcome_email_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="shareowner",
            name="attended_welcome_session",
            field=models.BooleanField(
                default=False, verbose_name="Attended Welcome Session"
            ),
        ),
    ]
