# Generated by Django 3.1.8 on 2021-06-04 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coop", "0012_shareowner_attended_welcome_session"),
    ]

    operations = [
        migrations.AlterField(
            model_name="draftuser",
            name="preferred_language",
            field=models.CharField(
                choices=[("de", "🇩🇪 Deutsch"), ("en", "🇬🇧 English")],
                default="de",
                max_length=16,
                verbose_name="Preferred Language",
            ),
        ),
        migrations.AlterField(
            model_name="shareowner",
            name="preferred_language",
            field=models.CharField(
                blank=True,
                choices=[("de", "🇩🇪 Deutsch"), ("en", "🇬🇧 English")],
                default="de",
                max_length=16,
                verbose_name="Preferred Language",
            ),
        ),
    ]
