# Generated by Django 3.1.8 on 2021-06-07 09:53

import django.contrib.postgres.fields.hstore
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("log", "0002_enable_hstore"),
        ("coop", "0014_updateshareownerlogentry"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeleteShareOwnershipLogEntry",
            fields=[
                (
                    "logentry_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="log.logentry",
                    ),
                ),
                ("values", django.contrib.postgres.fields.hstore.HStoreField()),
            ],
            options={
                "abstract": False,
            },
            bases=("log.logentry",),
        ),
        migrations.AlterField(
            model_name="shareowner",
            name="is_company",
            field=models.BooleanField(default=False, verbose_name="Is company"),
        ),
        migrations.AlterField(
            model_name="shareowner",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="share_owner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
