# Generated by Django 3.1.13 on 2021-07-29 18:40

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("coop", "0016_shareowner_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="draftuser",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, region=None, verbose_name="Phone Number"
            ),
        ),
        migrations.AlterField(
            model_name="shareowner",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, region=None, verbose_name="Phone Number"
            ),
        ),
    ]
