# Generated by Django 3.1.13 on 2021-10-15 07:10

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coop", "0018_remove_draftuser_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="shareowner",
            name="paid_membership_fee",
            field=models.BooleanField(default=True, verbose_name="Paid Membership Fee"),
        ),
        migrations.AlterField(
            model_name="draftuser",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, region=None, verbose_name="Phone number"
            ),
        ),
        migrations.AlterField(
            model_name="shareowner",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, region=None, verbose_name="Phone number"
            ),
        ),
    ]
