# Generated by Django 3.1.13 on 2021-10-15 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coop", "0020_auto_20211015_0937"),
    ]

    operations = [
        migrations.AddField(
            model_name="shareowner",
            name="willing_to_gift_a_share",
            field=models.DateField(
                blank=True, null=True, verbose_name="Is willing to gift a share"
            ),
        ),
    ]
