# Generated by Django 3.2.10 on 2022-01-28 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coop", "0021_shareowner_willing_to_gift_a_share"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="draftuser",
            name="from_startnext",
        ),
        migrations.RemoveField(
            model_name="draftuser",
            name="startnext_welcome_email_sent",
        ),
        migrations.RemoveField(
            model_name="shareowner",
            name="from_startnext",
        ),
    ]
