# Generated by Django 3.2.11 on 2022-01-30 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("coop", "0022_remove_from_startnext_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancingCampaign",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Currently active"),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Name")),
                ("goal", models.IntegerField(verbose_name="Goal")),
            ],
        ),
        migrations.CreateModel(
            name="FinancingSource",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Name")),
                ("raised_amount", models.IntegerField(verbose_name="Raised amount")),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="coop.financingcampaign",
                    ),
                ),
            ],
        ),
    ]
