# Generated by Django 3.2.11 on 2022-02-06 09:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coop", "0023_financingcampaign_financingsource"),
    ]

    operations = [
        migrations.AddField(
            model_name="shareownership",
            name="amount_paid",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("100"), max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="financingsource",
            name="raised_amount",
            field=models.IntegerField(default=0, verbose_name="Raised amount"),
        ),
    ]
