# Generated by Django 3.2.13 on 2022-06-04 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("coop", "0026_auto_20220422_1152"),
    ]

    operations = [
        migrations.CreateModel(
            name="IncomingPayment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.PositiveIntegerField(verbose_name="Amount")),
                ("payment_date", models.DateField(verbose_name="Payment date")),
                ("creation_date", models.DateField(verbose_name="Creation date")),
                ("comment", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "credited_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credited_member",
                        to="coop.shareowner",
                        verbose_name="Credited member",
                    ),
                ),
                (
                    "paying_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="paying_member",
                        to="coop.shareowner",
                        verbose_name="Paying member",
                    ),
                ),
            ],
        ),
    ]
