# Generated by Django 3.2.13 on 2022-06-05 10:00

import django.db.models.deletion
from django.db import migrations, models

import tapir.utils.models


class Migration(migrations.Migration):
    dependencies = [
        ("coop", "0027_incomingpayment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incomingpayment",
            name="amount",
            field=models.FloatField(
                validators=[tapir.utils.models.positive_number_validator],
                verbose_name="Amount",
            ),
        ),
        migrations.AlterField(
            model_name="incomingpayment",
            name="credited_member",
            field=models.ForeignKey(
                help_text="In almost all cases, the credited member is the same as the paying member. Only if a person if giting another person a share, through the matching program, then the fields can be different.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="credited_member",
                to="coop.shareowner",
                verbose_name="Credited member",
            ),
        ),
    ]
