# Generated by Django 3.2.15 on 2022-10-09 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coop", "0031_auto_20220918_1446"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shareownership",
            old_name="owner",
            new_name="share_owner",
        ),
    ]
