# Generated by Django 3.2.16 on 2022-10-22 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coop", "0033_rename_owner_shareownership_share_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="financingsource",
            name="campaign",
        ),
        migrations.DeleteModel(
            name="FinancingCampaign",
        ),
        migrations.DeleteModel(
            name="FinancingSource",
        ),
    ]
