# Generated by Django 3.2.16 on 2023-05-08 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coop", "0034_auto_20221022_1032"),
    ]

    operations = [
        migrations.AddField(
            model_name="draftuser",
            name="pronouns",
            field=models.CharField(blank=True, max_length=150, verbose_name="Pronouns"),
        ),
        migrations.AddField(
            model_name="draftuser",
            name="usage_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Usage name"
            ),
        ),
        migrations.AddField(
            model_name="shareowner",
            name="pronouns",
            field=models.CharField(blank=True, max_length=150, verbose_name="Pronouns"),
        ),
        migrations.AddField(
            model_name="shareowner",
            name="usage_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Usage name"
            ),
        ),
    ]
