# Generated by Django 3.2.16 on 2023-06-05 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coop", "0035_auto_20230508_1821"),
    ]

    operations = [
        migrations.AlterField(
            model_name="draftuser",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Administrative first name"
            ),
        ),
        migrations.AlterField(
            model_name="draftuser",
            name="usage_name",
            field=models.CharField(
                blank=True,
                help_text="Optional. If filled, will be used instead of the administrative first name wherever possible. Only official documents will show the administrative first name.",
                max_length=150,
                verbose_name="Usage name",
            ),
        ),
        migrations.AlterField(
            model_name="shareowner",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Administrative first name"
            ),
        ),
        migrations.AlterField(
            model_name="shareowner",
            name="usage_name",
            field=models.CharField(
                blank=True,
                help_text="Optional. If filled, will be used instead of the administrative first name wherever possible. Only official documents will show the administrative first name.",
                max_length=150,
                verbose_name="Usage name",
            ),
        ),
    ]
