# Generated by Django 3.2.23 on 2023-12-05 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("coop", "0038_alter_membershippause_share_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="draftuser",
            name="share_owner",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="draft_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
