# Generated by Django 3.2.23 on 2023-12-05 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coop", "0039_draftuser_share_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="draftuser",
            name="share_owner",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="draft_user",
                to="coop.shareowner",
            ),
        ),
    ]
