# Generated by Django 3.2.23 on 2024-03-19 11:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0041_auto_20231221_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareownership',
            name='cancellation_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.CreateModel(
            name='ResignedMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancellation_date', models.DateField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(max_length=1000)),
                ('coop_buys_shares_back', models.BooleanField()),
                ('willing_to_gift_shares_to_coop', models.BooleanField()),
                ('share_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coop.shareowner', verbose_name='Shareowner')),
            ],
        ),
    ]
