# Generated by Django 3.2.23 on 2024-06-01 16:34

import django.contrib.postgres.fields.hstore
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("log", "0006_alter_emaillogentry_email_content"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("coop", "0041_auto_20231221_1403"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResignMembershipCreateLogEntry",
            fields=[
                (
                    "logentry_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="log.logentry",
                    ),
                ),
                ("values", django.contrib.postgres.fields.hstore.HStoreField()),
            ],
            options={
                "abstract": False,
            },
            bases=("log.logentry",),
        ),
        migrations.CreateModel(
            name="ResignMembershipUpdateLogEntry",
            fields=[
                (
                    "logentry_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="log.logentry",
                    ),
                ),
                ("old_values", django.contrib.postgres.fields.hstore.HStoreField()),
                ("new_values", django.contrib.postgres.fields.hstore.HStoreField()),
            ],
            options={
                "abstract": False,
            },
            bases=("log.logentry",),
        ),
        migrations.CreateModel(
            name="ResignedMembership",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cancellation_date",
                    models.DateField(blank=True, default=django.utils.timezone.now),
                ),
                ("pay_out_day", models.DateField(null=True)),
                ("cancellation_reason", models.CharField(max_length=1000)),
                ("coop_buys_shares_back", models.BooleanField()),
                ("willing_to_gift_shares_to_coop", models.BooleanField()),
                ("paid_out", models.BooleanField(default=False)),
                (
                    "share_owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="coop.shareowner",
                        verbose_name="Shareowner",
                    ),
                ),
                (
                    "transfering_shares_to",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="TapirUser",
                    ),
                ),
            ],
        ),
    ]
