# Generated by Django 3.2.25 on 2024-07-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "coop",
            "0042_membershipresignation_membershipresignationcreatelogentry_membershipresignationupdatelogentry",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="membershipresignation",
            old_name="transfering_shares_to",
            new_name="transferring_shares_to",
        ),
        migrations.RemoveField(
            model_name="membershipresignation",
            name="coop_buys_shares_back",
        ),
        migrations.RemoveField(
            model_name="membershipresignation",
            name="willing_to_gift_shares_to_coop",
        ),
        migrations.AddField(
            model_name="membershipresignation",
            name="resignation_type",
            field=models.CharField(
                choices=[
                    (
                        "coop_buys_shares_back",
                        "The cooperative buys the shares back from the member",
                    ),
                    ("gift_to_coop", "The member gifts the shares to the cooperative"),
                    ("transfer", "The shares get transferred to another member"),
                ],
                default="coop_buys_shares_back",
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
