# Generated by Django 3.2.23 on 2024-04-03 20:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0042_auto_20240319_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='resignedmembership',
            name='paid_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='resignedmembership',
            name='cancellation_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 4, 3, 20, 52, 2, 484356, tzinfo=utc), null=True),
        ),
    ]
