# Generated by Django 3.2.23 on 2024-06-18 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "coop",
            "0042_resignedmembership_resignmembershipcreatelogentry_resignmembershipupdatelogentry",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="resignedmembership",
            name="share_owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="share_owner",
                to="coop.shareowner",
                verbose_name="Shareowner",
            ),
        ),
        migrations.AlterField(
            model_name="resignedmembership",
            name="transfering_shares_to",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owner_to_transfer",
                to="coop.shareowner",
                verbose_name="OwnerToTransfer",
            ),
        ),
    ]
