# Generated by Django 3.2.23 on 2024-04-03 21:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0043_auto_20240403_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resignedmembership',
            name='cancellation_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 4, 3, 21, 1, 45, 498750, tzinfo=utc), null=True),
        ),
    ]
