# Generated by Django 3.2.23 on 2024-04-03 21:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0044_alter_resignedmembership_cancellation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resignedmembership',
            name='cancellation_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 4, 3, 21, 35, 22, 494389, tzinfo=utc), null=True),
        ),
    ]
