# Generated by Django 3.2.23 on 2024-04-03 21:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coop', '0045_alter_resignedmembership_cancellation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='resignedmembership',
            name='transfering_shares_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='TapirUser'),
        ),
        migrations.AlterField(
            model_name='resignedmembership',
            name='cancellation_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 4, 3, 21, 50, 43, 829933, tzinfo=utc), null=True),
        ),
    ]
