# Generated by Django 5.1.2 on 2024-11-08 12:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coop", "0046_deleteincomingpaymentlogentry"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="membershippause",
            options={},
        ),
        migrations.AddIndex(
            model_name="membershippause",
            index=models.Index(
                fields=["share_owner"], name="coop_member_share_o_df09e3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shareowner",
            index=models.Index(
                fields=["is_investing"], name="coop_shareo_is_inve_4dabdb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shareownership",
            index=models.Index(
                fields=["start_date"], name="coop_shareo_start_d_12a59c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shareownership",
            index=models.Index(
                fields=["end_date"], name="coop_shareo_end_dat_af3b23_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shareownership",
            index=models.Index(
                fields=["start_date", "end_date"], name="coop_shareo_start_d_8367aa_idx"
            ),
        ),
    ]
