# Generated by Django 3.2.23 on 2024-05-06 09:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0046_auto_20240403_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='resignedmembership',
            name='pay_out_day',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='resignedmembership',
            name='cancellation_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 5, 6, 9, 46, 20, 243645, tzinfo=utc), null=True),
        ),
    ]
