# Generated by Django 3.2.23 on 2024-05-07 08:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0047_auto_20240506_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resignedmembership',
            name='cancellation_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 5, 7, 8, 42, 36, 563930, tzinfo=utc), null=True),
        ),
    ]
