# Generated by Django 5.1.1 on 2024-11-09 16:53

import django.contrib.postgres.fields.hstore
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coop", "0047_alter_membershippause_options_and_more"),
        ("log", "0007_auto_20240702_1748"),
    ]

    operations = [
        migrations.CreateModel(
            name="MembershipResignationDeleteLogEntry",
            fields=[
                (
                    "logentry_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="log.logentry",
                    ),
                ),
                ("values", django.contrib.postgres.fields.hstore.HStoreField()),
            ],
            options={
                "abstract": False,
            },
            bases=("log.logentry",),
        ),
        migrations.AlterField(
            model_name="membershipresignation",
            name="transferring_shares_to",
            field=models.ForeignKey(
                help_text="Leave this empty if the resignation type is not a transfer to another member",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="owner_to_transfer",
                to="coop.shareowner",
                verbose_name="OwnerToTransfer",
            ),
        ),
    ]
