# Generated by Django 3.2.23 on 2024-05-15 11:31

import datetime
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0007_auto_20240319_1242'),
        ('coop', '0048_alter_resignedmembership_cancellation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResignMembershipCreateLogEntry',
            fields=[
                ('logentry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='log.logentry')),
                ('values', django.contrib.postgres.fields.hstore.HStoreField()),
            ],
            options={
                'abstract': False,
            },
            bases=('log.logentry',),
        ),
        migrations.CreateModel(
            name='ResignMembershipUpdateLogEntry',
            fields=[
                ('logentry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='log.logentry')),
                ('old_values', django.contrib.postgres.fields.hstore.HStoreField()),
                ('new_values', django.contrib.postgres.fields.hstore.HStoreField()),
            ],
            options={
                'abstract': False,
            },
            bases=('log.logentry',),
        ),
        migrations.AlterField(
            model_name='resignedmembership',
            name='cancellation_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 5, 15, 11, 31, 18, 181204, tzinfo=utc), null=True),
        ),
    ]
