# Generated by Django 5.1.3 on 2024-12-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coop", "0050_alter_shareownership_transferred_from"),
    ]

    operations = [
        migrations.AddField(
            model_name="membershipresignation",
            name="cancellation_reason_category",
            field=models.CharField(
                choices=[
                    ("financial", "Financial reasons"),
                    ("health", "Health reasons"),
                    ("distance", "Distance"),
                    ("strategy", "Strategic orientation of SuperCoop"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
