# Generated by Django 3.2.23 on 2024-06-01 13:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0050_auto_20240522_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resignedmembership',
            name='cancellation_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
