# Generated by Django 5.1.5 on 2025-02-10 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coop", "0053_remove_shareowner_paid_membership_fee"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="draftuser",
            name="paid_shares",
        ),
    ]
