# Generated by Django 5.1.12 on 2025-10-01 10:24

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coop", "0054_remove_draftuser_paid_shares"),
        ("log", "0008_logentry_log_logentr_user_id_c4ca60_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="membershippauseupdatedlogentry",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["old_values"], name="coop_member_old_val_6e6554_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="membershippauseupdatedlogentry",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["new_values"], name="coop_member_new_val_5d0361_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="membershipresignationupdatelogentry",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["old_values"], name="coop_member_old_val_781bd5_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="membershipresignationupdatelogentry",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["new_values"], name="coop_member_new_val_077fd5_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="updateincomingpaymentlogentry",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["old_values"], name="coop_update_old_val_3dc8c2_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="updateincomingpaymentlogentry",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["new_values"], name="coop_update_new_val_1c42a5_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="updateshareownerlogentry",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["old_values"], name="coop_update_old_val_ec658b_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="updateshareownerlogentry",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["new_values"], name="coop_update_new_val_edfb49_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="updateshareownershiplogentry",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["old_values"], name="coop_update_old_val_ca0ffb_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="updateshareownershiplogentry",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["new_values"], name="coop_update_new_val_958538_gin"
            ),
        ),
    ]
