# Generated by Django 5.2.17 on 2026-09-03 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "coop",
            "0055_membershippauseupdatedlogentry_coop_member_old_val_6e6554_gin_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="draftuser",
            name="company_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="draftuser",
            name="is_company",
            field=models.BooleanField(default=False, verbose_name="Is company"),
        ),
    ]
