# Generated by Django 5.1.5 on 2025-06-23 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coop", "0055_shareowner_external_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shareowner",
            name="external_id",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
