# Generated by Django 5.2.17 on 2026-08-31 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "coop",
            "0055_membershippauseupdatedlogentry_coop_member_old_val_6e6554_gin_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="draftuser",
            name="is_company",
            field=models.BooleanField(default=False, verbose_name="Is company"),
        ),
    ]
