# Generated by Django 5.2.16 on 2026-07-18 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "coop",
            "0055_membershippauseupdatedlogentry_coop_member_old_val_6e6554_gin_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CoopAddress",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "coop_name",
                    models.CharField(default="SuperCoop Berlin", max_length=255),
                ),
                (
                    "coop_full_name",
                    models.CharField(
                        blank=True, default="SuperCoop Berlin eG", max_length=255
                    ),
                ),
                (
                    "street",
                    models.CharField(default="Oudenarder Straße 16", max_length=255),
                ),
                ("place", models.CharField(default="13347 Berlin", max_length=255)),
                ("country", models.CharField(default="Deutschland", max_length=255)),
            ],
        ),
    ]
