# Generated by Django 5.2.7 on 2025-11-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "coop",
            "0055_membershippauseupdatedlogentry_coop_member_old_val_6e6554_gin_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="draftuser",
            name="preferred_language",
            field=models.CharField(
                choices=[
                    ("de", "🇩🇪 Deutsch"),
                    ("en", "🇬🇧 English"),
                    ("pt", "🇵🇹 Portuguese"),
                ],
                default="de",
                max_length=16,
                verbose_name="Preferred Language",
            ),
        ),
        migrations.AlterField(
            model_name="shareowner",
            name="preferred_language",
            field=models.CharField(
                blank=True,
                choices=[
                    ("de", "🇩🇪 Deutsch"),
                    ("en", "🇬🇧 English"),
                    ("pt", "🇵🇹 Portuguese"),
                ],
                default="de",
                max_length=16,
                verbose_name="Preferred Language",
            ),
        ),
    ]
