# Generated by Django 5.1.12 on 2025-10-05 08:15

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "coop",
            "0055_membershippauseupdatedlogentry_coop_member_old_val_6e6554_gin_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="shareowner",
            managers=[
                ("everything", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="shareowner",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
