# Generated by Django 5.2.16 on 2026-07-18 07:09

from django.db import migrations


def create_default_coop_address(apps, schema_editor):
    CoopAddress = apps.get_model("coop", "CoopAddress")
    CoopAddress.objects.get_or_create()


def delete_default_coop_address(apps, schema_editor):
    CoopAddress = apps.get_model("coop", "CoopAddress")
    CoopAddress.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("coop", "0056_coopaddress"),
    ]

    operations = [
        migrations.RunPython(create_default_coop_address, delete_default_coop_address),
    ]
