# Generated by Django 5.1.12 on 2025-11-16 14:01

import django.contrib.postgres.fields.hstore
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coop", "0056_alter_shareowner_managers_shareowner_deleted_at"),
        ("log", "0008_logentry_log_logentr_user_id_c4ca60_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeleteShareOwnerLogEntry",
            fields=[
                (
                    "logentry_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="log.logentry",
                    ),
                ),
                ("values", django.contrib.postgres.fields.hstore.HStoreField()),
            ],
            options={
                "abstract": False,
            },
            bases=("log.logentry",),
        ),
    ]
