# Generated by Django 5.2.17 on 2026-10-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coop", "0056_draftuser_company_name_draftuser_is_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="draftuser",
            name="registration_origin",
            field=models.CharField(
                choices=[
                    ("online_self_registration", "Online"),
                    ("offline_form", "Paper form"),
                ],
                default="offline_form",
                max_length=40,
                verbose_name="Registration origin",
            ),
        ),
    ]
