# Generated by Django 5.2.17 on 2026-08-31 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coop", "0056_draftuser_is_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="draftuser",
            name="company_name",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
