# Generated by Django 5.1.12 on 2025-11-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coop", "0057_deleteshareownerlogentry"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="shareowner",
            managers=[],
        ),
        migrations.AlterField(
            model_name="shareowner",
            name="deleted_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
