openapi: 3.0.3
info:
  title: ''
  version: 0.0.0
paths:
  /statistics/available_datasets:
    get:
      operationId: statistics_available_datasets_list
      description: Verify that the current user is authenticated.
      tags:
      - statistics
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Dataset'
          description: ''
  /statistics/available_export_columns:
    get:
      operationId: statistics_available_export_columns_list
      description: Verify that the current user is authenticated.
      tags:
      - statistics
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Column'
          description: ''
  /welcomedesk/api/search:
    get:
      operationId: welcomedesk_api_search_list
      description: Verify that the current user is authenticated.
      parameters:
      - in: query
        name: search_input
        schema:
          type: string
        required: true
      tags:
      - welcomedesk
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ShareOwnerForWelcomeDesk'
          description: ''
components:
  schemas:
    Column:
      type: object
      properties:
        column_name:
          type: string
      required:
      - column_name
    Dataset:
      type: object
      properties:
        id:
          type: string
        display_name:
          type: string
        description:
          type: string
        color:
          type: string
        point_style:
          type: string
      required:
      - color
      - description
      - display_name
      - id
      - point_style
    ShareOwnerForWelcomeDesk:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        display_name:
          type: string
          readOnly: true
        can_shop:
          type: boolean
          readOnly: true
        co_purchaser:
          type: string
          nullable: true
          readOnly: true
        warnings:
          type: array
          items:
            type: string
          readOnly: true
        reasons_cannot_shop:
          type: array
          items:
            type: string
          readOnly: true
      required:
      - can_shop
      - co_purchaser
      - display_name
      - id
      - reasons_cannot_shop
      - warnings
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
