openapi: 3.0.3
info:
  title: ''
  version: 0.0.0
paths:
  /statistics/number_of_active_members_at_date:
    get:
      operationId: statistics_number_of_active_members_at_date_retrieve
      description: Verify that the current user is authenticated.
      parameters:
      - in: query
        name: at_date
        schema:
          type: string
          format: date
        required: true
      tags:
      - statistics
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: integer
          description: ''
  /statistics/number_of_members_at_date:
    get:
      operationId: statistics_number_of_members_at_date_retrieve
      description: Verify that the current user is authenticated.
      parameters:
      - in: query
        name: at_date
        schema:
          type: string
          format: date
        required: true
      tags:
      - statistics
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: integer
          description: ''
  /statistics/number_of_working_members_at_date:
    get:
      operationId: statistics_number_of_working_members_at_date_retrieve
      description: Verify that the current user is authenticated.
      parameters:
      - in: query
        name: at_date
        schema:
          type: string
          format: date
        required: true
      tags:
      - statistics
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: integer
          description: ''
  /welcomedesk/api/search:
    get:
      operationId: welcomedesk_api_search_list
      description: Verify that the current user is authenticated.
      parameters:
      - in: query
        name: search_input
        schema:
          type: string
        required: true
      tags:
      - welcomedesk
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ShareOwnerForWelcomeDesk'
          description: ''
components:
  schemas:
    ShareOwnerForWelcomeDesk:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        display_name:
          type: string
          readOnly: true
        can_shop:
          type: boolean
          readOnly: true
        co_purchaser:
          type: string
          nullable: true
          readOnly: true
        warnings:
          type: array
          items:
            type: string
          readOnly: true
        reasons_cannot_shop:
          type: array
          items:
            type: string
          readOnly: true
      required:
      - can_shop
      - co_purchaser
      - display_name
      - id
      - reasons_cannot_shop
      - warnings
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
