openapi: 3.0.3
info:
  title: ''
  version: 0.0.0
paths:
  /coop/member_self_register:
    post:
      operationId: coop_member_self_register_create
      tags:
      - coop
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MemberRegistrationRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/MemberRegistrationRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/MemberRegistrationRequest'
        required: true
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: boolean
          description: ''
  /statistics/available_colourblindness_types:
    get:
      operationId: statistics_available_colourblindness_types_retrieve
      description: Verify that the current user is authenticated.
      tags:
      - statistics
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
          description: ''
  /statistics/available_datasets:
    get:
      operationId: statistics_available_datasets_list
      description: Verify that the current user is authenticated.
      parameters:
      - in: query
        name: colourblindness
        schema:
          type: string
        required: true
      tags:
      - statistics
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Dataset'
          description: ''
  /statistics/available_export_columns:
    get:
      operationId: statistics_available_export_columns_list
      description: Verify that the current user is authenticated.
      tags:
      - statistics
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Column'
          description: ''
  /statistics/export_dataset:
    get:
      operationId: statistics_export_dataset_list
      description: Verify that the current user is authenticated.
      parameters:
      - in: query
        name: at_date
        schema:
          type: string
          format: date
        required: true
      - in: query
        name: dataset
        schema:
          type: string
        required: true
      - in: query
        name: export_columns
        schema:
          type: array
          items:
            type: string
        required: true
      tags:
      - statistics
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DatapointExport'
          description: ''
  /statistics/graph_point:
    get:
      operationId: statistics_graph_point_retrieve
      description: Verify that the current user is authenticated.
      parameters:
      - in: query
        name: at_date
        schema:
          type: string
          format: date
        required: true
      - in: query
        name: dataset
        schema:
          type: string
        required: true
      - in: query
        name: relative
        schema:
          type: boolean
        required: true
      tags:
      - statistics
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: integer
          description: ''
  /welcomedesk/api/search:
    get:
      operationId: welcomedesk_api_search_list
      description: Verify that the current user is authenticated.
      parameters:
      - in: query
        name: search_input
        schema:
          type: string
        required: true
      tags:
      - welcomedesk
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ShareOwnerForWelcomeDesk'
          description: ''
components:
  schemas:
    Column:
      type: object
      properties:
        column_name:
          type: string
      required:
      - column_name
    DatapointExport:
      type: object
      properties:
        member_number:
          type: integer
        display_name:
          type: string
        is_company:
          type: boolean
        company_name:
          type: string
        first_name:
          type: string
        last_name:
          type: string
        usage_name:
          type: string
        pronouns:
          type: string
        email:
          type: string
        phone_number:
          type: string
        birthdate:
          type: string
        street:
          type: string
        street_2:
          type: string
        postcode:
          type: string
        city:
          type: string
        country:
          type: string
        preferred_language:
          type: string
        is_investing:
          type: boolean
        ratenzahlung:
          type: boolean
        attended_welcome_session:
          type: boolean
        co_purchaser:
          type: string
        allows_purchase_tracking:
          type: boolean
        shift_capabilities:
          type: array
          items:
            type: string
        shift_partner:
          type: integer
        shift_status:
          type: string
        is_working:
          type: boolean
        is_exempted:
          type: boolean
        is_paused:
          type: boolean
        can_shop:
          type: boolean
        currently_paid:
          type: number
          format: double
        expected_payment:
          type: number
          format: double
        payment_difference:
          type: number
          format: double
        frozen_since:
          type: string
          format: date
        member_status:
          type: string
        is_member_since:
          type: string
          format: date
        legal_name:
          type: string
        full_address:
          type: string
        compulsory_share:
          type: integer
        additional_shares:
          type: integer
        amount_paid_for_entry_fee:
          type: number
          format: double
        amount_paid_for_shares:
          type: number
          format: double
        number_of_paid_shares:
          type: integer
        number_of_unpaid_shares:
          type: integer
    Dataset:
      type: object
      properties:
        id:
          type: string
        display_name:
          type: string
        description:
          type: string
        color:
          type: string
        point_style:
          type: string
      required:
      - color
      - description
      - display_name
      - id
      - point_style
    MemberRegistrationRequest:
      type: object
      properties:
        email:
          type: string
          format: email
        first_name:
          type: string
        last_name:
          type: string
        number_of_coop_shares:
          type: integer
      required:
      - email
      - first_name
      - last_name
      - number_of_coop_shares
    ShareOwnerForWelcomeDesk:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        display_name:
          type: string
          readOnly: true
        can_shop:
          type: boolean
          readOnly: true
        co_purchaser:
          type: string
          nullable: true
          readOnly: true
        co_purchaser_2:
          type: string
          nullable: true
          readOnly: true
        warnings:
          type: array
          items:
            type: string
          readOnly: true
        reasons_cannot_shop:
          type: array
          items:
            type: string
          readOnly: true
      required:
      - can_shop
      - co_purchaser
      - co_purchaser_2
      - display_name
      - id
      - reasons_cannot_shop
      - warnings
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
