sonar.projectKey=SuperCoopBerlin_tapir
sonar.organization=supercoopberlin
sonar.python.version=3.13
sonar.python.coverage.reportPaths=coverage.xml
sonar.coverage.exclusions=**/tests/*, **/tests/**/*, **/migrations/**, **/*.js, **/*.ts, manage.py, **/urls.py, **/*.tsx
sonar.cpd.exclusions=**/*.default.html, **/tests/*
sonar.exclusions=**/api-client/**,tapir/utils/management/commands/test_users.json, **/migrations/**, **/*.pdf,\
  **/*.png,**/*.woff,**/*.woff2,**/*.ico