# Generated by Django 3.1.14 on 2021-12-17 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("odoo", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OdooPartner",
        ),
    ]
