/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  MemberRegistrationRequest,
} from '../models/index';
import {
    MemberRegistrationRequestFromJSON,
    MemberRegistrationRequestToJSON,
} from '../models/index';

export interface CoopMemberSelfRegisterCreateRequest {
    memberRegistrationRequest: MemberRegistrationRequest;
}

/**
 * 
 */
export class CoopApi extends runtime.BaseAPI {

    /**
     */
    async coopMemberSelfRegisterCreateRaw(requestParameters: CoopMemberSelfRegisterCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<boolean>> {
        if (requestParameters['memberRegistrationRequest'] == null) {
            throw new runtime.RequiredError(
                'memberRegistrationRequest',
                'Required parameter "memberRegistrationRequest" was null or undefined when calling coopMemberSelfRegisterCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/coop/member_self_register`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MemberRegistrationRequestToJSON(requestParameters['memberRegistrationRequest']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<boolean>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     */
    async coopMemberSelfRegisterCreate(requestParameters: CoopMemberSelfRegisterCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<boolean> {
        const response = await this.coopMemberSelfRegisterCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
