/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateShiftSlotWarningRequest,
  CreateShiftUserCapabilityRequest,
  Language,
  PatchedUpdateShiftSlotWarningRequest,
  PatchedUpdateShiftUserCapabilityRequest,
  ShiftSlotWarning,
  ShiftUserCapability,
} from '../models/index';
import {
    CreateShiftSlotWarningRequestFromJSON,
    CreateShiftSlotWarningRequestToJSON,
    CreateShiftUserCapabilityRequestFromJSON,
    CreateShiftUserCapabilityRequestToJSON,
    LanguageFromJSON,
    LanguageToJSON,
    PatchedUpdateShiftSlotWarningRequestFromJSON,
    PatchedUpdateShiftSlotWarningRequestToJSON,
    PatchedUpdateShiftUserCapabilityRequestFromJSON,
    PatchedUpdateShiftUserCapabilityRequestToJSON,
    ShiftSlotWarningFromJSON,
    ShiftSlotWarningToJSON,
    ShiftUserCapabilityFromJSON,
    ShiftUserCapabilityToJSON,
} from '../models/index';

export interface ShiftsApiShiftSlotWarningCreateRequest {
    createShiftSlotWarningRequest: CreateShiftSlotWarningRequest;
}

export interface ShiftsApiShiftSlotWarningDestroyRequest {
    id: number;
}

export interface ShiftsApiShiftSlotWarningPartialUpdateRequest {
    patchedUpdateShiftSlotWarningRequest?: PatchedUpdateShiftSlotWarningRequest;
}

export interface ShiftsApiShiftUserCapabilityCreateRequest {
    createShiftUserCapabilityRequest: CreateShiftUserCapabilityRequest;
}

export interface ShiftsApiShiftUserCapabilityDestroyRequest {
    id: number;
}

export interface ShiftsApiShiftUserCapabilityPartialUpdateRequest {
    patchedUpdateShiftUserCapabilityRequest?: PatchedUpdateShiftUserCapabilityRequest;
}

export interface ShiftsShiftSlotWarningsRetrieveRequest {
    id: number;
}

export interface ShiftsShiftUserCapabilitiesRetrieveRequest {
    id: number;
}

/**
 * 
 */
export class ShiftsApi extends runtime.BaseAPI {

    /**
     * Verify that the current user has all specified permissions.
     */
    async shiftsApiLanguagesListRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Language>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/shifts/api/languages`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(LanguageFromJSON));
    }

    /**
     * Verify that the current user has all specified permissions.
     */
    async shiftsApiLanguagesList(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Language>> {
        const response = await this.shiftsApiLanguagesListRaw(initOverrides);
        return await response.value();
    }

    /**
     * Verify that the current user has all specified permissions.
     */
    async shiftsApiShiftSlotWarningCreateRaw(requestParameters: ShiftsApiShiftSlotWarningCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<number>> {
        if (requestParameters['createShiftSlotWarningRequest'] == null) {
            throw new runtime.RequiredError(
                'createShiftSlotWarningRequest',
                'Required parameter "createShiftSlotWarningRequest" was null or undefined when calling shiftsApiShiftSlotWarningCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/shifts/api/shift_slot_warning`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateShiftSlotWarningRequestToJSON(requestParameters['createShiftSlotWarningRequest']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<number>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Verify that the current user has all specified permissions.
     */
    async shiftsApiShiftSlotWarningCreate(requestParameters: ShiftsApiShiftSlotWarningCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<number> {
        const response = await this.shiftsApiShiftSlotWarningCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Verify that the current user has all specified permissions.
     */
    async shiftsApiShiftSlotWarningDestroyRaw(requestParameters: ShiftsApiShiftSlotWarningDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling shiftsApiShiftSlotWarningDestroy().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/shifts/api/shift_slot_warning`,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Verify that the current user has all specified permissions.
     */
    async shiftsApiShiftSlotWarningDestroy(requestParameters: ShiftsApiShiftSlotWarningDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.shiftsApiShiftSlotWarningDestroyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Verify that the current user has all specified permissions.
     */
    async shiftsApiShiftSlotWarningPartialUpdateRaw(requestParameters: ShiftsApiShiftSlotWarningPartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/shifts/api/shift_slot_warning`,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PatchedUpdateShiftSlotWarningRequestToJSON(requestParameters['patchedUpdateShiftSlotWarningRequest']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Verify that the current user has all specified permissions.
     */
    async shiftsApiShiftSlotWarningPartialUpdate(requestParameters: ShiftsApiShiftSlotWarningPartialUpdateRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.shiftsApiShiftSlotWarningPartialUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Verify that the current user has all specified permissions.
     */
    async shiftsApiShiftUserCapabilityCreateRaw(requestParameters: ShiftsApiShiftUserCapabilityCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<number>> {
        if (requestParameters['createShiftUserCapabilityRequest'] == null) {
            throw new runtime.RequiredError(
                'createShiftUserCapabilityRequest',
                'Required parameter "createShiftUserCapabilityRequest" was null or undefined when calling shiftsApiShiftUserCapabilityCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/shifts/api/shift_user_capability`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateShiftUserCapabilityRequestToJSON(requestParameters['createShiftUserCapabilityRequest']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<number>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Verify that the current user has all specified permissions.
     */
    async shiftsApiShiftUserCapabilityCreate(requestParameters: ShiftsApiShiftUserCapabilityCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<number> {
        const response = await this.shiftsApiShiftUserCapabilityCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Verify that the current user has all specified permissions.
     */
    async shiftsApiShiftUserCapabilityDestroyRaw(requestParameters: ShiftsApiShiftUserCapabilityDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling shiftsApiShiftUserCapabilityDestroy().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/shifts/api/shift_user_capability`,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Verify that the current user has all specified permissions.
     */
    async shiftsApiShiftUserCapabilityDestroy(requestParameters: ShiftsApiShiftUserCapabilityDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.shiftsApiShiftUserCapabilityDestroyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Verify that the current user has all specified permissions.
     */
    async shiftsApiShiftUserCapabilityPartialUpdateRaw(requestParameters: ShiftsApiShiftUserCapabilityPartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/shifts/api/shift_user_capability`,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PatchedUpdateShiftUserCapabilityRequestToJSON(requestParameters['patchedUpdateShiftUserCapabilityRequest']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Verify that the current user has all specified permissions.
     */
    async shiftsApiShiftUserCapabilityPartialUpdate(requestParameters: ShiftsApiShiftUserCapabilityPartialUpdateRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.shiftsApiShiftUserCapabilityPartialUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Verify that the current user has all specified permissions.
     */
    async shiftsShiftSlotWarningsListRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ShiftSlotWarning>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/shifts/shift_slot_warnings/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ShiftSlotWarningFromJSON));
    }

    /**
     * Verify that the current user has all specified permissions.
     */
    async shiftsShiftSlotWarningsList(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ShiftSlotWarning>> {
        const response = await this.shiftsShiftSlotWarningsListRaw(initOverrides);
        return await response.value();
    }

    /**
     * Verify that the current user has all specified permissions.
     */
    async shiftsShiftSlotWarningsRetrieveRaw(requestParameters: ShiftsShiftSlotWarningsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ShiftSlotWarning>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling shiftsShiftSlotWarningsRetrieve().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/shifts/shift_slot_warnings/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ShiftSlotWarningFromJSON(jsonValue));
    }

    /**
     * Verify that the current user has all specified permissions.
     */
    async shiftsShiftSlotWarningsRetrieve(requestParameters: ShiftsShiftSlotWarningsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ShiftSlotWarning> {
        const response = await this.shiftsShiftSlotWarningsRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Verify that the current user has all specified permissions.
     */
    async shiftsShiftUserCapabilitiesListRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ShiftUserCapability>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/shifts/shift_user_capabilities/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ShiftUserCapabilityFromJSON));
    }

    /**
     * Verify that the current user has all specified permissions.
     */
    async shiftsShiftUserCapabilitiesList(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ShiftUserCapability>> {
        const response = await this.shiftsShiftUserCapabilitiesListRaw(initOverrides);
        return await response.value();
    }

    /**
     * Verify that the current user has all specified permissions.
     */
    async shiftsShiftUserCapabilitiesRetrieveRaw(requestParameters: ShiftsShiftUserCapabilitiesRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ShiftUserCapability>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling shiftsShiftUserCapabilitiesRetrieve().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/shifts/shift_user_capabilities/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ShiftUserCapabilityFromJSON(jsonValue));
    }

    /**
     * Verify that the current user has all specified permissions.
     */
    async shiftsShiftUserCapabilitiesRetrieve(requestParameters: ShiftsShiftUserCapabilitiesRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ShiftUserCapability> {
        const response = await this.shiftsShiftUserCapabilitiesRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
