/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

/**
 * 
 */
export class ShiftsApi extends runtime.BaseAPI {

    /**
     */
    async shiftsSolidarityShiftsGiftedSolidarityShiftsJsonRetrieveRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/shifts/solidarity_shifts/gifted_solidarity_shifts_json`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async shiftsSolidarityShiftsGiftedSolidarityShiftsJsonRetrieve(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.shiftsSolidarityShiftsGiftedSolidarityShiftsJsonRetrieveRaw(initOverrides);
    }

    /**
     */
    async shiftsSolidarityShiftsUsedSolidarityShiftsJsonRetrieveRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/shifts/solidarity_shifts/used_solidarity_shifts_json`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async shiftsSolidarityShiftsUsedSolidarityShiftsJsonRetrieve(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.shiftsSolidarityShiftsUsedSolidarityShiftsJsonRetrieveRaw(initOverrides);
    }

}
