/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Column,
  Dataset,
} from '../models/index';
import {
    ColumnFromJSON,
    ColumnToJSON,
    DatasetFromJSON,
    DatasetToJSON,
} from '../models/index';

/**
 * 
 */
export class StatisticsApi extends runtime.BaseAPI {

    /**
     * Verify that the current user is authenticated.
     */
    async statisticsAvailableDatasetsListRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Dataset>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/statistics/available_datasets`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(DatasetFromJSON));
    }

    /**
     * Verify that the current user is authenticated.
     */
    async statisticsAvailableDatasetsList(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Dataset>> {
        const response = await this.statisticsAvailableDatasetsListRaw(initOverrides);
        return await response.value();
    }

    /**
     * Verify that the current user is authenticated.
     */
    async statisticsAvailableExportColumnsListRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Column>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/statistics/available_export_columns`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ColumnFromJSON));
    }

    /**
     * Verify that the current user is authenticated.
     */
    async statisticsAvailableExportColumnsList(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Column>> {
        const response = await this.statisticsAvailableExportColumnsListRaw(initOverrides);
        return await response.value();
    }

}
