/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ShareOwnerForWelcomeDesk,
} from '../models/index';
import {
    ShareOwnerForWelcomeDeskFromJSON,
    ShareOwnerForWelcomeDeskToJSON,
} from '../models/index';

export interface WelcomedeskApiSearchListRequest {
    searchInput: string;
}

/**
 * 
 */
export class WelcomedeskApi extends runtime.BaseAPI {

    /**
     */
    async welcomedeskApiSearchListRaw(requestParameters: WelcomedeskApiSearchListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ShareOwnerForWelcomeDesk>>> {
        if (requestParameters['searchInput'] == null) {
            throw new runtime.RequiredError(
                'searchInput',
                'Required parameter "searchInput" was null or undefined when calling welcomedeskApiSearchList().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['searchInput'] != null) {
            queryParameters['search_input'] = requestParameters['searchInput'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/welcomedesk/api/search`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ShareOwnerForWelcomeDeskFromJSON));
    }

    /**
     */
    async welcomedeskApiSearchList(requestParameters: WelcomedeskApiSearchListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ShareOwnerForWelcomeDesk>> {
        const response = await this.welcomedeskApiSearchListRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
