/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Column
 */
export interface Column {
    /**
     * 
     * @type {string}
     * @memberof Column
     */
    columnName: string;
}

/**
 * Check if a given object implements the Column interface.
 */
export function instanceOfColumn(value: object): value is Column {
    if (!('columnName' in value) || value['columnName'] === undefined) return false;
    return true;
}

export function ColumnFromJSON(json: any): Column {
    return ColumnFromJSONTyped(json, false);
}

export function ColumnFromJSONTyped(json: any, ignoreDiscriminator: boolean): Column {
    if (json == null) {
        return json;
    }
    return {
        
        'columnName': json['column_name'],
    };
}

  export function ColumnToJSON(json: any): Column {
      return ColumnToJSONTyped(json, false);
  }

  export function ColumnToJSONTyped(value?: Column | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'column_name': value['columnName'],
    };
}

