/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateShiftSlotWarningRequest
 */
export interface CreateShiftSlotWarningRequest {
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof CreateShiftSlotWarningRequest
     */
    translations: { [key: string]: any; };
}

/**
 * Check if a given object implements the CreateShiftSlotWarningRequest interface.
 */
export function instanceOfCreateShiftSlotWarningRequest(value: object): value is CreateShiftSlotWarningRequest {
    if (!('translations' in value) || value['translations'] === undefined) return false;
    return true;
}

export function CreateShiftSlotWarningRequestFromJSON(json: any): CreateShiftSlotWarningRequest {
    return CreateShiftSlotWarningRequestFromJSONTyped(json, false);
}

export function CreateShiftSlotWarningRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateShiftSlotWarningRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'translations': json['translations'],
    };
}

  export function CreateShiftSlotWarningRequestToJSON(json: any): CreateShiftSlotWarningRequest {
      return CreateShiftSlotWarningRequestToJSONTyped(json, false);
  }

  export function CreateShiftSlotWarningRequestToJSONTyped(value?: CreateShiftSlotWarningRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'translations': value['translations'],
    };
}

