/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateShiftUserCapabilityRequest
 */
export interface CreateShiftUserCapabilityRequest {
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof CreateShiftUserCapabilityRequest
     */
    translations: { [key: string]: any; };
}

/**
 * Check if a given object implements the CreateShiftUserCapabilityRequest interface.
 */
export function instanceOfCreateShiftUserCapabilityRequest(value: object): value is CreateShiftUserCapabilityRequest {
    if (!('translations' in value) || value['translations'] === undefined) return false;
    return true;
}

export function CreateShiftUserCapabilityRequestFromJSON(json: any): CreateShiftUserCapabilityRequest {
    return CreateShiftUserCapabilityRequestFromJSONTyped(json, false);
}

export function CreateShiftUserCapabilityRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateShiftUserCapabilityRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'translations': json['translations'],
    };
}

  export function CreateShiftUserCapabilityRequestToJSON(json: any): CreateShiftUserCapabilityRequest {
      return CreateShiftUserCapabilityRequestToJSONTyped(json, false);
  }

  export function CreateShiftUserCapabilityRequestToJSONTyped(value?: CreateShiftUserCapabilityRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'translations': value['translations'],
    };
}

