/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { BlankEnum } from './BlankEnum';
import {
    instanceOfBlankEnum,
    BlankEnumFromJSON,
    BlankEnumFromJSONTyped,
    BlankEnumToJSON,
} from './BlankEnum';
import type { CountryEnum } from './CountryEnum';
import {
    instanceOfCountryEnum,
    CountryEnumFromJSON,
    CountryEnumFromJSONTyped,
    CountryEnumToJSON,
} from './CountryEnum';

/**
 * @type Land
 * 
 * @export
 */
export type Land = BlankEnum | CountryEnum;

export function LandFromJSON(json: any): Land {
    return LandFromJSONTyped(json, false);
}

export function LandFromJSONTyped(json: any, ignoreDiscriminator: boolean): Land {
    if (json == null) {
        return json;
    }
    if (instanceOfBlankEnum(json)) {
        return BlankEnumFromJSONTyped(json, true);
    }
    if (instanceOfCountryEnum(json)) {
        return CountryEnumFromJSONTyped(json, true);
    }

    return {} as any;
}

export function LandToJSON(value?: Land | null): any {
    if (value == null) {
        return value;
    }

    if (instanceOfBlankEnum(value)) {
        return BlankEnumToJSON(value as BlankEnum);
    }
    if (instanceOfCountryEnum(value)) {
        return CountryEnumToJSON(value as CountryEnum);
    }

    return {};
}

