/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedUpdateShiftSlotWarningRequest
 */
export interface PatchedUpdateShiftSlotWarningRequest {
    /**
     * 
     * @type {number}
     * @memberof PatchedUpdateShiftSlotWarningRequest
     */
    id?: number;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof PatchedUpdateShiftSlotWarningRequest
     */
    translations?: { [key: string]: any; };
}

/**
 * Check if a given object implements the PatchedUpdateShiftSlotWarningRequest interface.
 */
export function instanceOfPatchedUpdateShiftSlotWarningRequest(value: object): value is PatchedUpdateShiftSlotWarningRequest {
    return true;
}

export function PatchedUpdateShiftSlotWarningRequestFromJSON(json: any): PatchedUpdateShiftSlotWarningRequest {
    return PatchedUpdateShiftSlotWarningRequestFromJSONTyped(json, false);
}

export function PatchedUpdateShiftSlotWarningRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedUpdateShiftSlotWarningRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'translations': json['translations'] == null ? undefined : json['translations'],
    };
}

  export function PatchedUpdateShiftSlotWarningRequestToJSON(json: any): PatchedUpdateShiftSlotWarningRequest {
      return PatchedUpdateShiftSlotWarningRequestToJSONTyped(json, false);
  }

  export function PatchedUpdateShiftSlotWarningRequestToJSONTyped(value?: PatchedUpdateShiftSlotWarningRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'translations': value['translations'],
    };
}

