/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ShiftSlotWarningTranslation } from './ShiftSlotWarningTranslation';
import {
    ShiftSlotWarningTranslationFromJSON,
    ShiftSlotWarningTranslationFromJSONTyped,
    ShiftSlotWarningTranslationToJSON,
    ShiftSlotWarningTranslationToJSONTyped,
} from './ShiftSlotWarningTranslation';

/**
 * 
 * @export
 * @interface PatchedShiftSlotWarning
 */
export interface PatchedShiftSlotWarning {
    /**
     * 
     * @type {ShiftSlotWarningTranslation}
     * @memberof PatchedShiftSlotWarning
     */
    readonly translations?: ShiftSlotWarningTranslation;
}

/**
 * Check if a given object implements the PatchedShiftSlotWarning interface.
 */
export function instanceOfPatchedShiftSlotWarning(value: object): value is PatchedShiftSlotWarning {
    return true;
}

export function PatchedShiftSlotWarningFromJSON(json: any): PatchedShiftSlotWarning {
    return PatchedShiftSlotWarningFromJSONTyped(json, false);
}

export function PatchedShiftSlotWarningFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedShiftSlotWarning {
    if (json == null) {
        return json;
    }
    return {
        
        'translations': json['translations'] == null ? undefined : ShiftSlotWarningTranslationFromJSON(json['translations']),
    };
}

  export function PatchedShiftSlotWarningToJSON(json: any): PatchedShiftSlotWarning {
      return PatchedShiftSlotWarningToJSONTyped(json, false);
  }

  export function PatchedShiftSlotWarningToJSONTyped(value?: Omit<PatchedShiftSlotWarning, 'translations'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

