/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedUpdateShiftUserCapabilityRequest
 */
export interface PatchedUpdateShiftUserCapabilityRequest {
    /**
     * 
     * @type {number}
     * @memberof PatchedUpdateShiftUserCapabilityRequest
     */
    id?: number;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof PatchedUpdateShiftUserCapabilityRequest
     */
    translations?: { [key: string]: any; };
}

/**
 * Check if a given object implements the PatchedUpdateShiftUserCapabilityRequest interface.
 */
export function instanceOfPatchedUpdateShiftUserCapabilityRequest(value: object): value is PatchedUpdateShiftUserCapabilityRequest {
    return true;
}

export function PatchedUpdateShiftUserCapabilityRequestFromJSON(json: any): PatchedUpdateShiftUserCapabilityRequest {
    return PatchedUpdateShiftUserCapabilityRequestFromJSONTyped(json, false);
}

export function PatchedUpdateShiftUserCapabilityRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedUpdateShiftUserCapabilityRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'translations': json['translations'] == null ? undefined : json['translations'],
    };
}

  export function PatchedUpdateShiftUserCapabilityRequestToJSON(json: any): PatchedUpdateShiftUserCapabilityRequest {
      return PatchedUpdateShiftUserCapabilityRequestToJSONTyped(json, false);
  }

  export function PatchedUpdateShiftUserCapabilityRequestToJSONTyped(value?: PatchedUpdateShiftUserCapabilityRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'translations': value['translations'],
    };
}

