/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `de` - 🇩🇪 Deutsch
 * * `en` - 🇬🇧 English
 * @export
 */
export const PreferredLanguageEnum = {
    De: 'de',
    En: 'en'
} as const;
export type PreferredLanguageEnum = typeof PreferredLanguageEnum[keyof typeof PreferredLanguageEnum];


export function instanceOfPreferredLanguageEnum(value: any): boolean {
    for (const key in PreferredLanguageEnum) {
        if (Object.prototype.hasOwnProperty.call(PreferredLanguageEnum, key)) {
            if (PreferredLanguageEnum[key as keyof typeof PreferredLanguageEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PreferredLanguageEnumFromJSON(json: any): PreferredLanguageEnum {
    return PreferredLanguageEnumFromJSONTyped(json, false);
}

export function PreferredLanguageEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): PreferredLanguageEnum {
    return json as PreferredLanguageEnum;
}

export function PreferredLanguageEnumToJSON(value?: PreferredLanguageEnum | null): any {
    return value as any;
}

export function PreferredLanguageEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): PreferredLanguageEnum {
    return value as PreferredLanguageEnum;
}

