/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ShareOwnerForWelcomeDesk
 */
export interface ShareOwnerForWelcomeDesk {
    /**
     * 
     * @type {number}
     * @memberof ShareOwnerForWelcomeDesk
     */
    readonly id: number;
    /**
     * 
     * @type {string}
     * @memberof ShareOwnerForWelcomeDesk
     */
    readonly displayName: string;
    /**
     * 
     * @type {boolean}
     * @memberof ShareOwnerForWelcomeDesk
     */
    readonly canShop: boolean;
    /**
     * 
     * @type {string}
     * @memberof ShareOwnerForWelcomeDesk
     */
    readonly coPurchaser: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof ShareOwnerForWelcomeDesk
     */
    readonly warnings: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ShareOwnerForWelcomeDesk
     */
    readonly reasonsCannotShop: Array<string>;
}

/**
 * Check if a given object implements the ShareOwnerForWelcomeDesk interface.
 */
export function instanceOfShareOwnerForWelcomeDesk(value: object): value is ShareOwnerForWelcomeDesk {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('displayName' in value) || value['displayName'] === undefined) return false;
    if (!('canShop' in value) || value['canShop'] === undefined) return false;
    if (!('coPurchaser' in value) || value['coPurchaser'] === undefined) return false;
    if (!('warnings' in value) || value['warnings'] === undefined) return false;
    if (!('reasonsCannotShop' in value) || value['reasonsCannotShop'] === undefined) return false;
    return true;
}

export function ShareOwnerForWelcomeDeskFromJSON(json: any): ShareOwnerForWelcomeDesk {
    return ShareOwnerForWelcomeDeskFromJSONTyped(json, false);
}

export function ShareOwnerForWelcomeDeskFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShareOwnerForWelcomeDesk {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'displayName': json['display_name'],
        'canShop': json['can_shop'],
        'coPurchaser': json['co_purchaser'],
        'warnings': json['warnings'],
        'reasonsCannotShop': json['reasons_cannot_shop'],
    };
}

  export function ShareOwnerForWelcomeDeskToJSON(json: any): ShareOwnerForWelcomeDesk {
      return ShareOwnerForWelcomeDeskToJSONTyped(json, false);
  }

  export function ShareOwnerForWelcomeDeskToJSONTyped(value?: Omit<ShareOwnerForWelcomeDesk, 'id'|'display_name'|'can_shop'|'co_purchaser'|'warnings'|'reasons_cannot_shop'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

