/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LanguageEnum } from './LanguageEnum';
import {
    LanguageEnumFromJSON,
    LanguageEnumFromJSONTyped,
    LanguageEnumToJSON,
    LanguageEnumToJSONTyped,
} from './LanguageEnum';

/**
 * 
 * @export
 * @interface ShiftUserCapabilityTranslation
 */
export interface ShiftUserCapabilityTranslation {
    /**
     * 
     * @type {number}
     * @memberof ShiftUserCapabilityTranslation
     */
    readonly id: number;
    /**
     * 
     * @type {LanguageEnum}
     * @memberof ShiftUserCapabilityTranslation
     */
    language?: LanguageEnum;
    /**
     * 
     * @type {string}
     * @memberof ShiftUserCapabilityTranslation
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ShiftUserCapabilityTranslation
     */
    description: string;
}



/**
 * Check if a given object implements the ShiftUserCapabilityTranslation interface.
 */
export function instanceOfShiftUserCapabilityTranslation(value: object): value is ShiftUserCapabilityTranslation {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function ShiftUserCapabilityTranslationFromJSON(json: any): ShiftUserCapabilityTranslation {
    return ShiftUserCapabilityTranslationFromJSONTyped(json, false);
}

export function ShiftUserCapabilityTranslationFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShiftUserCapabilityTranslation {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'language': json['language'] == null ? undefined : LanguageEnumFromJSON(json['language']),
        'name': json['name'],
        'description': json['description'],
    };
}

  export function ShiftUserCapabilityTranslationToJSON(json: any): ShiftUserCapabilityTranslation {
      return ShiftUserCapabilityTranslationToJSONTyped(json, false);
  }

  export function ShiftUserCapabilityTranslationToJSONTyped(value?: Omit<ShiftUserCapabilityTranslation, 'id'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'language': LanguageEnumToJSON(value['language']),
        'name': value['name'],
        'description': value['description'],
    };
}

