# Generated by Django 3.2.21 on 2023-10-20 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("statistics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchasebasket",
            name="tapir_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
