# Generated by Django 5.1.2 on 2024-11-24 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("statistics", "0003_alter_purchasebasket_tapir_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessedCreditFiles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("processed_on", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="CreditAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("credit_date", models.DateTimeField()),
                ("credit_amount", models.FloatField()),
                ("credit_counter", models.IntegerField()),
                ("cashier", models.IntegerField()),
                ("info", models.CharField()),
                (
                    "tapir_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="statistics.processedcreditfiles",
                    ),
                ),
            ],
        ),
    ]
