# Generated by Django 5.1.3 on 2024-12-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("statistics", "0003_alter_purchasebasket_tapir_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="FancyGraphCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("view_name", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("value", models.IntegerField()),
            ],
        ),
    ]
