# Generated by Django 5.1.3 on 2024-12-09 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("statistics", "0004_fancygraphcache"),
        ("statistics", "0004_processedcreditfiles_creditaccount"),
    ]

    operations = []
