# Generated by Django 5.1.5 on 2025-01-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("statistics", "0005_merge_20241209_2116"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fancygraphcache",
            name="view_name",
        ),
        migrations.AddField(
            model_name="fancygraphcache",
            name="data_provider_name_name",
            field=models.CharField(default="unused", max_length=500),
            preserve_default=False,
        ),
    ]
