# Generated by Django 5.1.5 on 2025-01-30 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("statistics", "0006_remove_fancygraphcache_view_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fancygraphcache",
            old_name="data_provider_name_name",
            new_name="data_provider_name",
        ),
    ]
