# Generated by Django 3.1.8 on 2021-05-21 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shifts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shift",
            name="shift_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="generated_shifts",
                to="shifts.shifttemplate",
            ),
        ),
        migrations.AlterField(
            model_name="shiftattendance",
            name="account_entry",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shift_attendance",
                to="shifts.shiftaccountentry",
            ),
        ),
    ]
