# Generated by Django 3.1.8 on 2021-07-14 08:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shifts", "0004_auto_20210606_2051"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shifttemplategroup",
            name="week_index",
        ),
    ]
