# Generated by Django 3.1.13 on 2021-07-22 07:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shifts", "0006_auto_20210714_1017"),
    ]

    operations = [
        migrations.AddField(
            model_name="shiftuserdata",
            name="capabilities",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[("shift_coordinator", "Shift Coordinator")], max_length=128
                ),
                default=list,
                size=None,
            ),
        ),
    ]
