# Generated by Django 3.1.13 on 2021-07-22 07:36

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shifts", "0007_add_shift_user_capability"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shiftattendance",
            options={"ordering": ["slot__shift__start_time"]},
        ),
        migrations.RemoveField(
            model_name="shift",
            name="num_slots",
        ),
        migrations.RemoveField(
            model_name="shiftattendance",
            name="shift",
        ),
        migrations.RemoveField(
            model_name="shiftattendancetemplate",
            name="shift_template",
        ),
        migrations.RemoveField(
            model_name="shifttemplate",
            name="num_slots",
        ),
        migrations.CreateModel(
            name="ShiftSlotTemplate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                (
                    "required_capabilities",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[("shift_coordinator", "Shift Coordinator")],
                            max_length=128,
                        ),
                        default=list,
                        size=None,
                    ),
                ),
                ("optional", models.BooleanField(default=False)),
                (
                    "shift_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slot_templates",
                        to="shifts.shifttemplate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShiftSlot",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                (
                    "required_capabilities",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[("shift_coordinator", "Shift Coordinator")],
                            max_length=128,
                        ),
                        default=list,
                        size=None,
                    ),
                ),
                ("optional", models.BooleanField(default=False)),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="shifts.shift",
                    ),
                ),
                (
                    "slot_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="generated_slots",
                        to="shifts.shiftslottemplate",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="shiftattendance",
            name="slot",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attendances",
                to="shifts.shiftslot",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shiftattendancetemplate",
            name="slot_template",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attendance_template",
                to="shifts.shiftslottemplate",
            ),
            preserve_default=False,
        ),
    ]
