# Generated by Django 3.1.13 on 2021-08-23 12:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0011_add_shift_user_data_log_entry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shiftslot",
            name="required_capabilities",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[("shift_coordinator", "Shift Coordinator")], max_length=128
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="shiftslottemplate",
            name="required_capabilities",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[("shift_coordinator", "Shift Coordinator")], max_length=128
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
