# Generated by Django 3.1.13 on 2021-09-07 18:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0015_auto_20210905_1809"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shiftslot",
            name="required_capabilities",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("shift_coordinator", "Shift Coordinator"),
                        ("cashier", "Cashier"),
                    ],
                    max_length=128,
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="shiftslottemplate",
            name="required_capabilities",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("shift_coordinator", "Shift Coordinator"),
                        ("cashier", "Cashier"),
                    ],
                    max_length=128,
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="shiftuserdata",
            name="capabilities",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("shift_coordinator", "Shift Coordinator"),
                        ("cashier", "Cashier"),
                    ],
                    max_length=128,
                ),
                default=list,
                size=None,
            ),
        ),
    ]
