# Generated by Django 3.1.13 on 2021-09-15 09:37

import django.contrib.postgres.fields.hstore
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("log", "0003_textlogentry"),
        ("shifts", "0017_auto_20210914_1258"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShiftAttendanceTakenOverLogEntry",
            fields=[
                (
                    "logentry_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="log.logentry",
                    ),
                ),
                ("values", django.contrib.postgres.fields.hstore.HStoreField()),
                ("slot_name", models.CharField(blank=True, max_length=255)),
                ("state", models.IntegerField(null=True)),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="shifts.shift"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("log.logentry",),
        ),
    ]
