# Generated by Django 3.1.13 on 2021-09-19 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0019_auto_20210919_1137"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="shiftattendance",
            index=models.Index(fields=["state"], name="shifts_shif_state_3ba88d_idx"),
        ),
    ]
