# Generated by Django 3.1.13 on 2021-10-03 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0024_auto_20211003_0941"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShiftCycleLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cycle_start_date", models.DateField(verbose_name="Cycle start date")),
                (
                    "shift_account_entry",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shift_cycle_log",
                        to="shifts.shiftaccountentry",
                    ),
                ),
                (
                    "shift_user_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shift_cycle_logs",
                        to="shifts.shiftuserdata",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="shiftcyclelog",
            constraint=models.UniqueConstraint(
                fields=("shift_user_data", "cycle_start_date"),
                name="user_date_constraint",
            ),
        ),
    ]
