# Generated by Django 3.1.13 on 2021-10-15 06:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shifts", "0026_auto_20211005_1425"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shiftslot",
            name="required_capabilities",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("shift_coordinator", "Teamleader"),
                        ("cashier", "Cashier"),
                        ("member_office", "Member Office"),
                        ("bread_delivery", "Bread Delivery"),
                        ("red_card", "Red Card"),
                        ("first_aid", "First Aid"),
                    ],
                    max_length=128,
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="shiftslottemplate",
            name="required_capabilities",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("shift_coordinator", "Teamleader"),
                        ("cashier", "Cashier"),
                        ("member_office", "Member Office"),
                        ("bread_delivery", "Bread Delivery"),
                        ("red_card", "Red Card"),
                        ("first_aid", "First Aid"),
                    ],
                    max_length=128,
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="shiftuserdata",
            name="attendance_mode",
            field=models.CharField(
                choices=[("regular", "🏠 ABCD"), ("flying", "✈ Flying")],
                default="regular",
                max_length=32,
                verbose_name="Shift system",
            ),
        ),
        migrations.AlterField(
            model_name="shiftuserdata",
            name="capabilities",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("shift_coordinator", "Teamleader"),
                        ("cashier", "Cashier"),
                        ("member_office", "Member Office"),
                        ("bread_delivery", "Bread Delivery"),
                        ("red_card", "Red Card"),
                        ("first_aid", "First Aid"),
                    ],
                    max_length=128,
                ),
                default=list,
                size=None,
            ),
        ),
    ]
