# Generated by Django 3.1.13 on 2021-10-22 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0027_auto_20211015_0858"),
    ]

    operations = [
        migrations.AddField(
            model_name="shift",
            name="required_attendances",
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name="shifttemplate",
            name="required_attendances",
            field=models.IntegerField(default=3),
        ),
    ]
