# Generated by Django 3.1.13 on 2021-11-08 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0029_auto_20211022_0948"),
    ]

    operations = [
        migrations.AddField(
            model_name="shiftattendance",
            name="reminder_email_sent",
            field=models.BooleanField(default=False),
        ),
    ]
