# Generated by Django 3.1.13 on 2021-11-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0030_shiftattendance_reminder_email_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="shiftattendance",
            name="last_state_update",
            field=models.DateTimeField(null=True),
        ),
    ]
