# Generated by Django 3.2.13 on 2022-06-04 13:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0035_auto_20220430_0015"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shift",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Is shown on the shift page below the title",
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="shift",
            name="num_required_attendances",
            field=models.PositiveIntegerField(
                default=3,
                help_text="If there are less members registered to a shift than that number, it will be highlighted in the shift calendar.",
                null=True,
                verbose_name="Number of required attendances",
            ),
        ),
        migrations.AlterField(
            model_name="shiftslot",
            name="required_capabilities",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("shift_coordinator", "Teamleader"),
                        ("cashier", "Cashier"),
                        ("member_office", "Member Office"),
                        ("bread_delivery", "Bread Delivery"),
                        ("red_card", "Red Card"),
                        ("first_aid", "First Aid"),
                        ("welcome_session", "Welcome Session"),
                        ("handling_cheese", "Handling Cheese"),
                    ],
                    max_length=128,
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="shiftslottemplate",
            name="required_capabilities",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("shift_coordinator", "Teamleader"),
                        ("cashier", "Cashier"),
                        ("member_office", "Member Office"),
                        ("bread_delivery", "Bread Delivery"),
                        ("red_card", "Red Card"),
                        ("first_aid", "First Aid"),
                        ("welcome_session", "Welcome Session"),
                        ("handling_cheese", "Handling Cheese"),
                    ],
                    max_length=128,
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="shifttemplate",
            name="num_required_attendances",
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name="shiftuserdata",
            name="capabilities",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("shift_coordinator", "Teamleader"),
                        ("cashier", "Cashier"),
                        ("member_office", "Member Office"),
                        ("bread_delivery", "Bread Delivery"),
                        ("red_card", "Red Card"),
                        ("first_aid", "First Aid"),
                        ("welcome_session", "Welcome Session"),
                        ("handling_cheese", "Handling Cheese"),
                    ],
                    max_length=128,
                ),
                default=list,
                size=None,
            ),
        ),
    ]
