# Generated by Django 3.2.16 on 2022-11-20 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shifts", "0040_auto_20221009_1119"),
    ]

    operations = [
        migrations.AddField(
            model_name="shiftaccountentry",
            name="is_from_welcome_session",
            field=models.BooleanField(default=False),
        ),
    ]
