# Generated by Django 3.2.20 on 2023-08-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shifts", "0046_shifttemplate_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shifttemplate",
            name="start_date",
            field=models.DateField(
                blank=True,
                help_text="This determines from which date shifts should be generated from this ABCD shift.",
                null=True,
            ),
        ),
    ]
