# Generated by Django 3.2.22 on 2023-11-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shifts", "0048_auto_20231021_2102"),
    ]

    operations = [
        migrations.AddField(
            model_name="shiftattendance",
            name="is_solidarity",
            field=models.BooleanField(default=False),
        ),
    ]
