# Generated by Django 3.2.22 on 2023-11-05 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0049_shiftattendance_is_solidarity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shiftattendance",
            name="is_solidarity",
        ),
    ]
