# Generated by Django 3.2.22 on 2023-11-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0050_remove_shiftattendance_is_solidarity"),
    ]

    operations = [
        migrations.AddField(
            model_name="shiftattendance",
            name="is_solidarity",
            field=models.BooleanField(default=False),
        ),
    ]
