# Generated by Django 3.2.22 on 2023-11-07 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shifts", "0051_shiftattendance_is_solidarity"),
    ]

    operations = [
        migrations.CreateModel(
            name="SolidarityShift",
            fields=[
                (
                    "shiftAttendance",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="shifts.shiftattendance",
                    ),
                ),
                ("is_used_up", models.BooleanField(default=False)),
            ],
        ),
    ]
