# Generated by Django 3.2.22 on 2023-11-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shifts", "0053_auto_20231116_1130"),
    ]

    operations = [
        migrations.AddField(
            model_name="shiftaccountentry",
            name="is_solidarity_entry",
            field=models.BooleanField(default=False),
        ),
    ]
