# Generated by Django 3.2.23 on 2023-12-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0055_remove_shiftaccountentry_is_solidarity_entry"),
    ]

    operations = [
        migrations.AddField(
            model_name="shiftaccountentry",
            name="is_solidarity_used",
            field=models.BooleanField(default=False),
        ),
    ]
