# Generated by Django 3.2.23 on 2024-05-19 08:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0056_shiftaccountentry_is_solidarity_used"),
    ]

    operations = [
        migrations.AddField(
            model_name="shift",
            name="has_been_warned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="shift",
            name="warning_time",
            field=models.DurationField(
                default=datetime.timedelta(days=-1),
                help_text="Negative values deactivate function.\n The format is Day Hour:Minute:Second",
            ),
        ),
    ]
