# Generated by Django 3.2.23 on 2024-02-14 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0056_shiftaccountentry_is_solidarity_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftexemption',
            name='continue_abcd_shift',
            field=models.BooleanField(default=False, verbose_name='User continues their ABCD shift even with an active exemption'),
        ),
    ]
