# Generated by Django 3.2.25 on 2024-07-09 17:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shifts', '0056_shiftaccountentry_is_solidarity_used'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftWatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_timedelta', models.DurationField(default=datetime.timedelta(days=2))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shift_watched', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shifts.shift')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_watching_shift', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='shiftwatch',
            constraint=models.UniqueConstraint(fields=('user', 'shift_watched'), name='shift_watch_constraint'),
        ),
    ]
