# Generated by Django 3.2.25 on 2024-08-26 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0056_shiftaccountentry_is_solidarity_used"),
    ]

    operations = [
        migrations.AddField(
            model_name="shiftuserdata",
            name="shift_partner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shift_partner_of",
                to="shifts.shiftuserdata",
            ),
        ),
    ]
