# Generated by Django 3.2.25 on 2024-09-02 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0059_alter_shiftuserdata_shift_partner"),
    ]

    operations = [
        migrations.AddField(
            model_name="createshiftattendancetemplatelogentry",
            name="slot_template",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="shifts.shiftslottemplate",
            ),
        ),
        migrations.AddField(
            model_name="deleteshiftattendancetemplatelogentry",
            name="slot_template",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="shifts.shiftslottemplate",
            ),
        ),
    ]
