# Generated by Django 5.1.1 on 2024-10-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0060_auto_20240902_1022"),
    ]

    operations = [
        migrations.AddField(
            model_name="shift",
            name="flexible_time",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, members who register for that shift can choose themselves the time where they come do their shift.",
                verbose_name="Flexible time",
            ),
        ),
        migrations.AddField(
            model_name="shiftattendance",
            name="custom_time",
            field=models.TimeField(
                help_text="This shift lets you choose at what time you come during the day of the shift. In order to help organising the attendance, please specify when you expect to come.",
                null=True,
                verbose_name="Chosen time",
            ),
        ),
        migrations.AddField(
            model_name="shiftattendancetemplate",
            name="custom_time",
            field=models.TimeField(
                help_text="This shift lets you choose at what time you come during the day of the shift. In order to help organising the attendance, please specify when you expect to come.",
                null=True,
                verbose_name="Chosen time",
            ),
        ),
        migrations.AddField(
            model_name="shifttemplate",
            name="flexible_time",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, members who register for that shift can choose themselves the time where they come do their shift.",
                verbose_name="Flexible time",
            ),
        ),
    ]
