# Generated by Django 5.1.2 on 2024-11-08 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0062_alter_shift_end_time_alter_shift_start_time_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="shiftexemption",
            index=models.Index(
                fields=["start_date"], name="shifts_shif_start_d_8c1069_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shiftexemption",
            index=models.Index(
                fields=["end_date"], name="shifts_shif_end_dat_ea0268_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shiftexemption",
            index=models.Index(
                fields=["start_date", "end_date"], name="shifts_shif_start_d_abfc0c_idx"
            ),
        ),
    ]
