# Generated by Django 5.1.2 on 2024-11-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0064_remove_shiftuserdata_attendance_mode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deleteshiftattendancetemplatelogentry",
            name="comment",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
