# Generated by Django 5.1.4 on 2025-01-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0065_deleteshiftattendancetemplatelogentry_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="shifttemplate",
            name="monthweek",
            field=models.IntegerField(
                blank=True,
                choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                null=True,
                verbose_name="Repeat in calendar weeks",
            ),
        ),
        migrations.AlterField(
            model_name="shifttemplate",
            name="weekday",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "Monday"),
                    (1, "Tuesday"),
                    (2, "Wednesday"),
                    (3, "Thursday"),
                    (4, "Friday"),
                    (5, "Saturday"),
                ],
                null=True,
                verbose_name="Repeat in weekdays",
            ),
        ),
    ]
