# Generated by Django 5.1.5 on 2025-02-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0065_deleteshiftattendancetemplatelogentry_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shift",
            name="cancelled_reason",
            field=models.CharField(
                max_length=1000, null=True, verbose_name="Cancellation reason"
            ),
        ),
    ]
