# Generated by Django 5.1.5 on 2025-08-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0067_shift_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shift",
            name="num_required_attendances",
            field=models.PositiveIntegerField(
                default=0,
                help_text="If there are less members registered to a shift than that number, it will be highlighted in the shift calendar.",
                null=True,
                verbose_name="Number of required attendances",
            ),
        ),
        migrations.AlterField(
            model_name="shifttemplate",
            name="num_required_attendances",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
