# Generated by Django 5.1.5 on 2025-08-11 08:12

import datetime
import django.db.models.deletion
import tapir.shifts.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0067_shift_deleted"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShiftStaffingStatus",
            fields=[
                (
                    "shift",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="shifts.shift",
                    ),
                ),
                (
                    "staffing_status",
                    models.CharField(
                        choices=tapir.shifts.models.get_statuses,
                        default="(Unknown)",
                        max_length=2,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ShiftWatch",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_reason_for_notification",
                    models.CharField(
                        choices=tapir.shifts.models.get_statuses, max_length=2
                    ),
                ),
                (
                    "notification_timedelta",
                    models.DurationField(default=datetime.timedelta(days=2)),
                ),
                ("notification_sent", models.BooleanField(default=False)),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shifts.shift"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_watching_shift",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "shift"), name="shift_watch_constraint"
                    )
                ],
            },
        ),
    ]
