# Generated by Django 5.1.5 on 2025-08-22 08:11

import datetime
import django.contrib.postgres.fields
import django.db.models.deletion
import tapir.shifts.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0067_shift_deleted"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShiftWatch",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "staffing_events",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=tapir.shifts.models.get_staffingevent_choices,
                            max_length=30,
                        ),
                        default=tapir.shifts.models.get_staffingevent_defaults,
                        size=None,
                    ),
                ),
                (
                    "last_reason_for_notification",
                    models.CharField(
                        choices=tapir.shifts.models.get_staffingevent_choices,
                        max_length=30,
                    ),
                ),
                (
                    "notification_timedelta",
                    models.DurationField(default=datetime.timedelta(days=2)),
                ),
                (
                    "last_valid_slot_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shifts.shift"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_watching_shift",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "shift"), name="shift_watch_constraint"
                    )
                ],
            },
        ),
    ]
