# Generated by Django 5.1.5 on 2025-06-12 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0069_auto_20250612_1231"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shiftslot",
            name="required_capabilities",
        ),
        migrations.RemoveField(
            model_name="shiftslottemplate",
            name="required_capabilities",
        ),
        migrations.RemoveField(
            model_name="shiftuserdata",
            name="capabilities",
        ),
    ]
