# Generated by Django 5.1.12 on 2025-10-01 10:24

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("log", "0008_logentry_log_logentr_user_id_c4ca60_idx_and_more"),
        ("shifts", "0069_shiftwatch"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="updateexemptionlogentry",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["old_values"], name="shifts_upda_old_val_689533_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="updateexemptionlogentry",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["new_values"], name="shifts_upda_new_val_9e6e1e_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="updateshiftuserdatalogentry",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["old_values"], name="shifts_upda_old_val_a320c1_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="updateshiftuserdatalogentry",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["new_values"], name="shifts_upda_new_val_6c5412_gin"
            ),
        ),
    ]
