# Generated by Django 5.1.5 on 2025-06-12 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0070_remove_shiftslot_required_capabilities_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shiftslot",
            old_name="required_capabilities_new",
            new_name="required_capabilities",
        ),
        migrations.RenameField(
            model_name="shiftslottemplate",
            old_name="required_capabilities_new",
            new_name="required_capabilities",
        ),
        migrations.RenameField(
            model_name="shiftuserdata",
            old_name="capabilities_new",
            new_name="capabilities",
        ),
    ]
