# Generated by Django 5.2.7 on 2025-11-20 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "shifts",
            "0070_updateexemptionlogentry_shifts_upda_old_val_689533_gin_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ShiftSlotWarningNew",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShiftUserCapabilityNew",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="shiftslot",
            name="warnings_new",
            field=models.ManyToManyField(to="shifts.shiftslotwarningnew"),
        ),
        migrations.AddField(
            model_name="shiftslottemplate",
            name="warnings_new",
            field=models.ManyToManyField(to="shifts.shiftslotwarningnew"),
        ),
        migrations.CreateModel(
            name="ShiftSlotWarningTranslation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("de", "🇩🇪 Deutsch"), ("en", "🇬🇧 English")],
                        default="de",
                        max_length=16,
                        verbose_name="Language",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "warning",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shifts.shiftslotwarningnew",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="shiftslot",
            name="required_capabilities_new",
            field=models.ManyToManyField(to="shifts.shiftusercapabilitynew"),
        ),
        migrations.AddField(
            model_name="shiftslottemplate",
            name="required_capabilities_new",
            field=models.ManyToManyField(to="shifts.shiftusercapabilitynew"),
        ),
        migrations.AddField(
            model_name="shiftuserdata",
            name="capabilities_new",
            field=models.ManyToManyField(to="shifts.shiftusercapabilitynew"),
        ),
        migrations.CreateModel(
            name="ShiftUserCapabilityTranslation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("de", "🇩🇪 Deutsch"), ("en", "🇬🇧 English")],
                        default="de",
                        max_length=16,
                        verbose_name="Language",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "capability",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shifts.shiftusercapabilitynew",
                    ),
                ),
            ],
        ),
    ]
