# Generated by Django 5.2.7 on 2025-11-14 13:46

import django.contrib.postgres.fields
import django.db.models.deletion
import tapir.shifts.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "shifts",
            "0070_updateexemptionlogentry_shifts_upda_old_val_689533_gin_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShiftRecurringWatchTemplate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shift_template_group",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "weekdays",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(
                            blank=True,
                            choices=[
                                (0, "Monday"),
                                (1, "Tuesday"),
                                (2, "Wednesday"),
                                (3, "Thursday"),
                                (4, "Friday"),
                                (5, "Saturday"),
                                (6, "Sunday"),
                            ],
                            null=True,
                        ),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "staffing_status",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=tapir.shifts.models.get_staffingstatus_choices,
                            max_length=30,
                        ),
                        default=tapir.shifts.models.get_staffingstatus_defaults,
                        size=None,
                    ),
                ),
                (
                    "shift_templates",
                    models.ManyToManyField(blank=True, to="shifts.shifttemplate"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shift_recurring_watch",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="shiftwatch",
            name="recurring_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shift_watches",
                to="shifts.shiftrecurringwatchtemplate",
            ),
        ),
    ]
