# Generated by Django 5.1.5 on 2025-06-12 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "shifts",
            "0071_rename_required_capabilities_new_shiftslot_required_capabilities_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ShiftUserCapabilityNew",
            new_name="ShiftUserCapability",
        ),
    ]
