# Generated by Django 5.2.7 on 2025-11-07 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0071_shiftrecurringwatchtemplate"),
    ]

    operations = [
        migrations.AddField(
            model_name="shiftwatch",
            name="recurring_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shift_watches",
                to="shifts.shiftrecurringwatchtemplate",
            ),
        ),
    ]
