# Generated by Django 5.2.9 on 2025-12-23 08:55

import tapir.shifts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0071_recurringshiftwatch_shiftwatch_recurring_template"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shiftwatch",
            name="last_staffing_status",
            field=models.CharField(
                choices=tapir.shifts.models.get_staffingstatus_choices,
                default=None,
                max_length=30,
            ),
        ),
    ]
