# Generated by Django 5.2.11 on 2026-02-23 20:36

from django.db import migrations


def fix_null_last_staffing_status(apps, schema_editor):
    ShiftWatch = apps.get_model("shifts", "ShiftWatch")
    ShiftWatch.objects.filter(last_staffing_status__isnull=True).update(
        last_staffing_status="ALL_CLEAR"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0072_alter_shiftwatch_last_staffing_status"),
    ]

    operations = [
        migrations.RunPython(fix_null_last_staffing_status),
    ]
