# Generated by Django 5.1.5 on 2025-06-12 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0072_rename_shiftusercapabilitynew_shiftusercapability"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShiftSlotWarningNew",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="shiftslot",
            name="warnings_new",
            field=models.ManyToManyField(to="shifts.shiftslotwarningnew"),
        ),
        migrations.AddField(
            model_name="shiftslottemplate",
            name="warnings_new",
            field=models.ManyToManyField(to="shifts.shiftslotwarningnew"),
        ),
        migrations.CreateModel(
            name="ShiftSlotWarningTranslation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("de", "🇩🇪 Deutsch"), ("en", "🇬🇧 English")],
                        default="de",
                        max_length=16,
                        verbose_name="Language",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "warning",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shifts.shiftslotwarningnew",
                    ),
                ),
            ],
        ),
    ]
