# Generated by Django 5.2.7 on 2025-11-07 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0072_shiftwatch_recurring_template"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shiftrecurringwatchtemplate",
            name="abcd",
        ),
        migrations.AddField(
            model_name="shiftrecurringwatchtemplate",
            name="shift_template_group",
            field=models.ManyToManyField(blank=True, to="shifts.shifttemplategroup"),
        ),
    ]
