# Generated by Django 5.2.7 on 2025-11-20 15:42

from django.db import migrations


class ShiftSlotWarningOld:
    IN_THE_MORNING_EVERYONE_HELPS_STORAGE = "in_the_morning_everyone_helps_storage"
    IN_THE_EVENING_EVERYONE_HELPS_CLEAN = "in_the_evening_everyone_helps_clean"
    BREAD_PICKUP_NEEDS_A_VEHICLE = "bread_picked_needs_a_vehicle"
    MUST_BE_ABLE_TO_CARRY_HEAVY_WEIGHTS = "must_be_able_to_carry_heavy_weights"
    MUST_NOT_BE_SCARED_OF_HEIGHTS = "must_not_be_scared_of_heights"


SHIFT_SLOT_WARNING_CHOICES_OLD = {
    ShiftSlotWarningOld.IN_THE_MORNING_EVERYONE_HELPS_STORAGE: "I understand that all working groups help the Warenannahme & Lager working group until the shop opens.",
    ShiftSlotWarningOld.IN_THE_EVENING_EVERYONE_HELPS_CLEAN: "I understand that all working groups help the Reinigung & Aufräumen working group after the shop closes.",
    ShiftSlotWarningOld.BREAD_PICKUP_NEEDS_A_VEHICLE: "I understand that I need my own vehicle in order to pick up the bread. A cargo bike can be borrowed, more infos in Slack in the #cargobike channel",
    ShiftSlotWarningOld.MUST_BE_ABLE_TO_CARRY_HEAVY_WEIGHTS: "I understand that I may need to carry heavy weights for this shift.",
    ShiftSlotWarningOld.MUST_NOT_BE_SCARED_OF_HEIGHTS: "I understand that I may need to work high, for example up a ladder. I do not suffer from fear of heights.",
}

TRANSLATIONS = {
    ShiftSlotWarningOld.IN_THE_MORNING_EVERYONE_HELPS_STORAGE: "Ich bestätige, dass alle Arbeitsgruppen die Arbeitsgruppe Warenannahme & Lagerhaltung bis zur Eröffnung des Ladens unterstützen.",
    ShiftSlotWarningOld.MUST_BE_ABLE_TO_CARRY_HEAVY_WEIGHTS: "Mir ist klar, dass ich bei dieser Schicht möglicherweise schwere Gewichte heben muss.",
    ShiftSlotWarningOld.MUST_NOT_BE_SCARED_OF_HEIGHTS: "Mir ist klar, dass ich möglicherweise in großer Höhe arbeiten muss, zum Beispiel auf einer Leiter. Ich leide nicht unter Höhenangst.",
}


def create_new_warning_and_translations(apps, warning_old_id: str):
    shift_slot_warning_new_model = apps.get_model("shifts", "ShiftSlotWarningNew")
    shift_slot_warning_translation_model = apps.get_model(
        "shifts", "ShiftSlotWarningTranslation"
    )
    new_warning = shift_slot_warning_new_model.objects.create()
    english_name = SHIFT_SLOT_WARNING_CHOICES_OLD[warning_old_id]
    german_name = TRANSLATIONS.get(warning_old_id, "")
    shift_slot_warning_translation_model.objects.bulk_create(
        [
            shift_slot_warning_translation_model(
                language="en",
                name=english_name,
                description="",
                warning=new_warning,
            ),
            shift_slot_warning_translation_model(
                language="de",
                name=german_name,
                description="",
                warning=new_warning,
            ),
        ]
    )
    return new_warning


def populate_warnings_generic(
    apps,
    model,
    new_warnings_by_old_id: dict,
):
    for obj in model.objects.all():
        must_save_object = False
        for warning_old_id in obj.warnings:
            if warning_old_id not in new_warnings_by_old_id.keys():
                new_warnings_by_old_id[warning_old_id] = (
                    create_new_warning_and_translations(apps, warning_old_id)
                )
            obj.warnings_new.add(new_warnings_by_old_id[warning_old_id])
            must_save_object = True
        if must_save_object:
            obj.save()


def populate_all_new_warning_fields(apps, _):
    new_capabilities_by_old_id = {}

    for old_id in SHIFT_SLOT_WARNING_CHOICES_OLD:
        create_new_warning_and_translations(apps, old_id)

    shift_slot_template_model = apps.get_model("shifts", "ShiftSlotTemplate")
    populate_warnings_generic(
        apps, shift_slot_template_model, new_capabilities_by_old_id
    )

    shift_slot_model = apps.get_model("shifts", "ShiftSlot")
    populate_warnings_generic(apps, shift_slot_model, new_capabilities_by_old_id)


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0072_auto_20251120_1642"),
    ]

    operations = [
        migrations.RunPython(populate_all_new_warning_fields),
    ]
