# Generated by Django 5.2.7 on 2025-11-20 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0073_auto_20251120_1642"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shiftslot",
            name="required_capabilities",
        ),
        migrations.RemoveField(
            model_name="shiftslot",
            name="warnings",
        ),
        migrations.RemoveField(
            model_name="shiftslottemplate",
            name="required_capabilities",
        ),
        migrations.RemoveField(
            model_name="shiftslottemplate",
            name="warnings",
        ),
        migrations.RemoveField(
            model_name="shiftuserdata",
            name="capabilities",
        ),
    ]
