# Generated by Django 5.2.7 on 2025-11-07 20:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0073_remove_shiftrecurringwatchtemplate_abcd_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shiftrecurringwatchtemplate",
            name="shift_template_group",
        ),
        migrations.AddField(
            model_name="shiftrecurringwatchtemplate",
            name="shift_template_group",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("name", "index"),
                        ("name", "index"),
                        ("name", "index"),
                        ("name", "index"),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
