# Generated by Django 5.2.12 on 2026-03-13 15:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0073_alter_shiftwatch_last_staffing_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="shiftwatch",
            name="watched_capabilities",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("shift_coordinator", "Teamleader"),
                        ("cashier", "Cashier"),
                        ("member_office", "Member Office"),
                        ("bread_delivery", "Bread Delivery"),
                        ("red_card", "Red Card"),
                        ("first_aid", "First Aid"),
                        ("welcome_session", "Welcome Session"),
                        ("handling_cheese", "Handling Cheese"),
                        ("train_cheese_handlers", "Train cheese handlers"),
                        ("inventory", "Inventory"),
                        ("nebenan_de_support", "Nebenan.de-Support"),
                    ],
                    max_length=128,
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
