# Generated by Django 5.2.12 on 2026-03-15 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0073_alter_shiftwatch_last_staffing_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shift",
            name="num_required_attendances",
            field=models.PositiveIntegerField(
                default=0,
                help_text="If there are less members registered to a shift than that number, it will be highlighted in the shift calendar. The number of required attendances can't be higher than the slots in the resp. shift.",
                verbose_name="Number of required attendances",
            ),
        ),
    ]
