# Generated by Django 5.2.12 on 2026-03-13 21:00

import django.contrib.postgres.fields
import tapir.shifts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0073_alter_shiftwatch_last_staffing_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="shiftwatch",
            name="watched_capabilities",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=tapir.shifts.models.get_shift_capability_choices,
                    max_length=128,
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
