# Generated by Django 5.2.7 on 2025-11-07 20:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "shifts",
            "0074_remove_shiftrecurringwatchtemplate_shift_template_group_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="shiftrecurringwatchtemplate",
            name="shift_template_group",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
