# Generated by Django 5.2.7 on 2025-11-20 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0074_remove_shiftslot_required_capabilities_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shiftslot",
            old_name="required_capabilities_new",
            new_name="required_capabilities",
        ),
        migrations.RenameField(
            model_name="shiftslot",
            old_name="warnings_new",
            new_name="warnings",
        ),
        migrations.RenameField(
            model_name="shiftslottemplate",
            old_name="required_capabilities_new",
            new_name="required_capabilities",
        ),
        migrations.RenameField(
            model_name="shiftslottemplate",
            old_name="warnings_new",
            new_name="warnings",
        ),
        migrations.RenameField(
            model_name="shiftuserdata",
            old_name="capabilities_new",
            new_name="capabilities",
        ),
    ]
