# Generated by Django 5.1.5 on 2025-06-12 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0074_auto_20250612_1521"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shiftslot",
            name="warnings",
        ),
        migrations.RemoveField(
            model_name="shiftslottemplate",
            name="warnings",
        ),
    ]
