# Generated by Django 5.2.13 on 2026-04-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0074_alter_shift_num_required_attendances"),
    ]

    operations = [
        migrations.AddField(
            model_name="shifttemplate",
            name="end_date",
            field=models.DateField(
                blank=True,
                help_text="All shifts after this date will be cancelled.",
                null=True,
            ),
        ),
    ]
