# Generated by Django 5.1.5 on 2025-06-12 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0075_remove_shiftslot_warnings_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shiftslot",
            old_name="warnings_new",
            new_name="warnings",
        ),
        migrations.RenameField(
            model_name="shiftslottemplate",
            old_name="warnings_new",
            new_name="warnings",
        ),
    ]
