# Generated by Django 5.2.15 on 2026-06-14 18:50

import django.contrib.postgres.fields
import tapir.shifts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0075_shiftwatch_watched_capabilities"),
    ]

    operations = [
        migrations.AddField(
            model_name="recurringshiftwatch",
            name="watched_capabilities",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=tapir.shifts.models.get_shift_capability_choices,
                    max_length=128,
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
