# Generated by Django 5.2.7 on 2025-11-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "shifts",
            "0075_rename_required_capabilities_new_shiftslot_required_capabilities_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ShiftUserCapabilityNew",
            new_name="ShiftUserCapability",
        ),
        migrations.RenameModel(
            old_name="ShiftSlotWarningNew",
            new_name="ShiftSlotWarning",
        ),
        migrations.AlterField(
            model_name="shiftslotwarningtranslation",
            name="language",
            field=models.CharField(
                choices=[
                    ("de", "🇩🇪 Deutsch"),
                    ("en", "🇬🇧 English"),
                    ("pt", "🇵🇹 Portuguese"),
                ],
                default="de",
                max_length=16,
                verbose_name="Language",
            ),
        ),
        migrations.AlterField(
            model_name="shiftusercapabilitytranslation",
            name="language",
            field=models.CharField(
                choices=[
                    ("de", "🇩🇪 Deutsch"),
                    ("en", "🇬🇧 English"),
                    ("pt", "🇵🇹 Portuguese"),
                ],
                default="de",
                max_length=16,
                verbose_name="Language",
            ),
        ),
    ]
