# Generated by Django 5.1.5 on 2025-06-12 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0076_rename_warnings_new_shiftslot_warnings_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ShiftSlotWarningNew",
            new_name="ShiftSlotWarning",
        ),
    ]
