# Generated by Django 5.2.16 on 2026-08-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0076_recurringshiftwatch_watched_capabilities"),
    ]

    operations = [
        migrations.AddField(
            model_name="shifttemplate",
            name="end_date",
            field=models.DateField(
                blank=True,
                help_text="All shifts after this date will be cancelled.",
                null=True,
            ),
        ),
    ]
