# Generated by Django 5.1.5 on 2025-06-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0077_rename_shiftslotwarningnew_shiftslotwarning"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shiftslotwarningtranslation",
            name="language",
            field=models.CharField(
                choices=[
                    ("de", "🇩🇪 Deutsch"),
                    ("en", "🇬🇧 English"),
                    ("pt", "🇵🇹 Portugal"),
                ],
                default="de",
                max_length=16,
                verbose_name="Language",
            ),
        ),
        migrations.AlterField(
            model_name="shiftusercapabilitytranslation",
            name="language",
            field=models.CharField(
                choices=[
                    ("de", "🇩🇪 Deutsch"),
                    ("en", "🇬🇧 English"),
                    ("pt", "🇵🇹 Portugal"),
                ],
                default="de",
                max_length=16,
                verbose_name="Language",
            ),
        ),
    ]
