# Generated by Django 5.1.5 on 2025-09-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0078_alter_shiftslotwarningtranslation_language_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shiftattendance",
            name="external_event_id",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
