# Generated by Django 5.1.5 on 2025-09-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0079_shiftattendance_external_event_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="shiftslot",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
