# Generated by Django 5.1.5 on 2025-09-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0080_shiftslot_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="shiftslottemplate",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
