# Generated by Django 5.1.5 on 2025-09-29 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0081_shiftslottemplate_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="shifttemplate",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
