# Generated by Django 5.1.5 on 2025-10-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0082_shifttemplate_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="shiftattendance",
            name="second_reminder_email_sent",
            field=models.BooleanField(default=False),
        ),
    ]
