# Generated by Django 5.1.5 on 2025-07-07 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coop", "0056_alter_shareowner_external_id"),
        ("rizoma", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RizomaMemberData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo_id", models.CharField()),
                (
                    "share_owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rizoma_member_data",
                        to="coop.shareowner",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="RizomaUserData",
        ),
    ]
