# Generated by Django 5.1.5 on 2025-07-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rizoma", "0002_rizomamemberdata_delete_rizomauserdata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rizomamemberdata",
            name="photo_id",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
