# Generated by Django 3.1.8 on 2021-06-05 08:00
from django.contrib.postgres.operations import HStoreExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("log", "0001_initial"),
    ]

    operations = [HStoreExtension()]
