# Generated by Django 3.1.8 on 2021-07-07 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("log", "0002_enable_hstore"),
    ]

    operations = [
        migrations.CreateModel(
            name="TextLogEntry",
            fields=[
                (
                    "logentry_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="log.logentry",
                    ),
                ),
                ("text", models.TextField()),
            ],
            bases=("log.logentry",),
        ),
    ]
