# Generated by Django 3.2.16 on 2023-04-04 19:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("log", "0005_auto_20220821_0924"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emaillogentry",
            name="email_content",
            field=models.BinaryField(null=True),
        ),
    ]
