# Generated by Django 3.2.23 on 2024-06-28 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0042_membershipresignation_membershipresignationcreatelogentry_membershipresignationupdatelogentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('log', '0006_alter_emaillogentry_email_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='share_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='coop.shareowner'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to=settings.AUTH_USER_MODEL),
        ),
    ]
