# Generated by Django 5.2.17 on 2026-09-11 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coop", "0056_draftuser_company_name_draftuser_is_company"),
        ("log", "0008_logentry_log_logentr_user_id_c4ca60_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="logentry",
            name="draft_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="log_entries",
                to="coop.draftuser",
            ),
        ),
    ]
