# Generated by Django 3.2.16 on 2022-10-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuration", "0002_tapirparameter_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tapirparameter",
            name="datatype",
            field=models.CharField(max_length=8),
        ),
    ]
