# Generated by Django 3.2.16 on 2022-10-26 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("configuration", "0003_alter_tapirparameter_datatype"),
        ("configuration", "0003_tapirparameter_order_priority"),
    ]

    operations = []
