# Generated by Django 3.2.16 on 2023-03-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuration", "0004_merge_20221026_1426"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tapirparameter",
            name="value",
            field=models.CharField(max_length=1048576, null=True),
        ),
    ]
