# Generated by Django 3.1.8 on 2021-05-20 13:52

from django.db import migrations, models
import ldapdb.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_auto_20210406_1343"),
    ]

    operations = [
        migrations.AddField(
            model_name="tapiruser",
            name="preferred_language",
            field=models.CharField(
                choices=[("de", "Deutsch"), ("en", "English")],
                default="de",
                max_length=16,
                verbose_name="Preferred Language",
            ),
        ),
    ]
