# Generated by Django 3.1.8 on 2021-06-07 10:13

from django.db import migrations, models
import ldapdb.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_auto_20210520_1352"),
    ]

    operations = [
        migrations.AddField(
            model_name="tapiruser",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Phone number"
            ),
        ),
        migrations.AlterField(
            model_name="tapiruser",
            name="preferred_language",
            field=models.CharField(
                choices=[("de", "🇩🇪 Deutsch"), ("en", "🇬🇧 English")],
                default="de",
                max_length=16,
                verbose_name="Preferred Language",
            ),
        ),
    ]
