# Generated by Django 3.1.13 on 2021-10-15 06:58

from django.db import migrations, models
import ldapdb.models.fields
import phonenumber_field.modelfields
import tapir.accounts.validators


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_auto_20210909_0943"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tapiruser",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, region=None, verbose_name="Phone number"
            ),
        ),
        migrations.AlterField(
            model_name="tapiruser",
            name="username",
            field=models.CharField(
                error_messages={"unique": "A user with that username already exists."},
                help_text="Required. 150 characters or fewer. Letters, digits and ./-/_ only.",
                max_length=150,
                unique=True,
                validators=[tapir.accounts.validators.UsernameValidator()],
                verbose_name="Username",
            ),
        ),
    ]
