# Generated by Django 3.2.12 on 2022-04-22 09:52

from django.db import migrations, models
import ldapdb.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20211015_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='tapiruser',
            name='co_purchaser',
            field=models.CharField(blank=True, max_length=150, verbose_name='Co-Purchaser'),
        ),
    ]
