# Generated by Django 3.2.16 on 2022-12-24 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_auto_20220422_1152"),
    ]

    operations = [
        migrations.AddField(
            model_name="tapiruser",
            name="allows_purchase_tracking",
            field=models.BooleanField(
                default=False, verbose_name="Allow purchase tracking"
            ),
        ),
    ]
