# Generated by Django 3.2.16 on 2023-05-08 16:21

from django.db import migrations, models
import ldapdb.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_auto_20221224_1015"),
    ]

    operations = [
        migrations.AddField(
            model_name="tapiruser",
            name="pronouns",
            field=models.CharField(blank=True, max_length=150, verbose_name="Pronouns"),
        ),
        migrations.AddField(
            model_name="tapiruser",
            name="usage_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Usage name"
            ),
        ),
    ]
