# Generated by Django 3.2.16 on 2023-06-05 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_auto_20230508_1821"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tapiruser",
            name="usage_name",
            field=models.CharField(
                blank=True,
                help_text="Optional. If filled, will be used instead of the administrative first name wherever possible. Only official documents will show the administrative first name.",
                max_length=150,
                verbose_name="Displayed name",
            ),
        ),
    ]
