# Generated by Django 5.1.1 on 2024-10-26 17:01

import django.db.models.deletion
import tapir.core.tapir_email_base
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_auto_20240915_1113"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tapiruser",
            name="additional_mails",
        ),
        migrations.CreateModel(
            name="MailChoice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=tapir.core.tapir_email_base.get_optional_mails,
                        max_length=256,
                    ),
                ),
                ("choice", models.BooleanField()),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "choice"), name="mail-name-chosen-constraint"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OptionalMails",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.mailchoice",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mail_setting",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "mail"), name="user-mail-constraint"
                    )
                ],
            },
        ),
    ]
