# Generated by Django 5.1.1 on 2024-09-26 20:14

import django.contrib.postgres.fields
import tapir.accounts.models
import tapir.core.tapir_email_base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_auto_20240915_1113"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tapiruser",
            name="additional_mails",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=tapir.core.tapir_email_base.get_mails_not_mandatory,
                    max_length=128,
                ),
                blank=True,
                default=tapir.accounts.models.get_mails_not_mandatory_and_default,
                size=None,
            ),
        ),
    ]
