# Generated by Django 5.1.4 on 2025-01-06 11:08

import tapir.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_remove_tapiruser_additional_mails_optionalmails"),
    ]

    operations = [
        migrations.AlterField(
            model_name="optionalmails",
            name="mail_id",
            field=models.CharField(
                choices=tapir.accounts.models.get_optional_mail_choices_wrapper,
                max_length=256,
            ),
        ),
    ]
