# Generated by Django 5.1.5 on 2025-06-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_alter_optionalmails_mail_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="tapiruser",
            name="external_id",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="tapiruser",
            name="preferred_language",
            field=models.CharField(
                choices=[
                    ("de", "🇩🇪 Deutsch"),
                    ("en", "🇬🇧 English"),
                    ("pt", "🇵🇹 Portugal"),
                ],
                default="de",
                max_length=16,
                verbose_name="Preferred Language",
            ),
        ),
    ]
