# Generated by Django 5.1.5 on 2025-08-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_tapiruser_co_purchaser_2"),
    ]

    operations = [
        migrations.AddField(
            model_name="tapiruser",
            name="co_purchaser_2_mail",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Co-Purchaser mail"
            ),
        ),
        migrations.AddField(
            model_name="tapiruser",
            name="co_purchaser_mail",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Co-Purchaser mail"
            ),
        ),
    ]
