# Generated by Django 5.1.5 on 2025-08-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0020_tapiruser_co_purchaser_2_mail_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tapiruser",
            name="co_purchaser_2_mail",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Co-Purchaser mail 2"
            ),
        ),
    ]
