# Generated by Django 5.1.12 on 2025-10-01 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0021_alter_tapiruser_co_purchaser_2_mail"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tapiruser",
            options={},
        ),
        migrations.AddIndex(
            model_name="tapiruser",
            index=models.Index(
                fields=["date_joined"], name="accounts_ta_date_jo_38d2cd_idx"
            ),
        ),
    ]
