# Generated by Django 5.1.12 on 2025-10-01 10:24

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0022_alter_tapiruser_options_and_more"),
        ("log", "0008_logentry_log_logentr_user_id_c4ca60_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="updatetapiruserlogentry",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["old_values"], name="accounts_up_old_val_25b95f_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="updatetapiruserlogentry",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["new_values"], name="accounts_up_new_val_f7cd9c_gin"
            ),
        ),
    ]
