# Generated by Django 5.2.7 on 2025-11-27 08:47
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0023_updatetapiruserlogentry_accounts_up_old_val_25b95f_gin_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="tapiruser",
            name="preferred_language",
            field=models.CharField(
                choices=[
                    ("de", "🇩🇪 Deutsch"),
                    ("en", "🇬🇧 English"),
                    ("pt", "🇵🇹 Portuguese"),
                ],
                default=settings.LANGUAGE_CODE,
                max_length=16,
                verbose_name="Preferred Language",
            ),
        ),
    ]
