# Generated by Django 5.2.13 on 2026-04-26 17:02

from django.db import migrations


def split_name(full_name):
    if not full_name:
        return "", ""
    parts = full_name.strip().split()
    if len(parts) == 1:
        return parts[0], ""
    else:
        return " ".join(parts[:-1]), parts[-1]


def migrate_co_purchasers(apps, schema_editor):
    TapirUser = apps.get_model("accounts", "TapirUser")
    CoPurchaser = apps.get_model("accounts", "CoPurchaser")

    for user in TapirUser.objects.all():

        if user.co_purchaser:
            first_name, last_name = split_name(user.co_purchaser)
            CoPurchaser.objects.create(
                user=user,
                first_name=first_name,
                last_name=last_name,
                email=user.co_purchaser_mail,
                order=0,
            )
        if user.co_purchaser_2:
            first_name, last_name = split_name(user.co_purchaser_2)
            CoPurchaser.objects.create(
                user=user,
                first_name=first_name,
                last_name=last_name,
                email=user.co_purchaser_2_mail,
                order=1,
            )


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0024_copurchaser"),
    ]

    operations = [
        migrations.RunPython(migrate_co_purchasers),
    ]
