# Example: build your devcontainer and run poetry install + tests in CI
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  devcontainer-ci:
    runs-on: ubuntu-latest
    name: Build devcontainer image and run tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build devcontainer and run commands
        # Official devcontainers CI action builds the image from .devcontainer and runs commands inside it.
        # You can use a stable tag from the devcontainers/ci repo (check their README for the recommended tag).
        uses: devcontainers/ci@main
        with:
          # Path to the folder that contains devcontainer.json (default is root)
          # here it is the repository root which includes .devcontainer/
          repo: ${{ github.repository }}
          # N.B. runCmd will be executed inside the devcontainer. Use multiline commands as below.
          runCmd: |
            set -eux
            # make sure poetry is non-interactive and doesn't create venvs in CI environment
            poetry config virtualenvs.create false --local || true
            poetry install --no-interaction
            poetry run pytest -q